{
 "title": "GemFire Category Region Tables",
 "description": "Template for capturing region categories",
 "tags": [
  "all",
  "gemfire",
  "category",
  "region",
  "generated"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DiskRegionStatistics (Max)",
   "type": "table",
   "description": "$Cluster: DiskRegionStatistics - max values of all member stats per region",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max (gemfire_bytesOnlyOnDisk{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_entriesInVM{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_entriesOnlyOnDisk{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_localInitializations{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_readBytes{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_readTime{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_reads{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_remoteInitializations{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removeTime{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removes{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writeTime{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writes{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writtenBytes{$ClusterFilterLabel=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LeafDiskStoreStatistics (Max)",
   "type": "table",
   "description": "$Cluster: LeafDiskStoreStatistics - max values of all member stats per region",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max (gemfire_allocatedSegments{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_backupsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_backupsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactDeleteTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactDeletes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactInsertTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactInserts{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactUpdateTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactUpdates{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactableOplogs{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compacts{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_compactsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_flushTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_flushedBytes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_flushes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_flushesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_inactiveOplogs{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_maxSegments{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_openOplogs{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_oplogReads{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_oplogRecoveredBytes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_oplogRecoveries{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_oplogRecoveryTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_oplogSeeks{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_queueSize{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_readBytes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_readTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_reads{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveredBytes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveredEntryCreates{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveredEntryDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveredEntryUpdates{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveredValuesSkippedDueToLRU{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveriesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveryRecordsSkipped{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveryTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removeTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_uncreatedRecoveredRegions{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writeTime{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_writtenBytes{$ClusterFilterLabel=\"$Cluster\", category=\"LeafDiskStoreStatistics\"}) by (exported_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "McPartitionedRegionStats (Max)",
   "type": "table",
   "description": "$Cluster: McPartitionedRegionStats - max values of all member stats per region",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max (gemfire_primaryBucketsCount{$ClusterFilterLabel=\"$Cluster\", category=\"McPartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryBucketsSize{$ClusterFilterLabel=\"$Cluster\", category=\"McPartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_redundantBucketsCount{$ClusterFilterLabel=\"$Cluster\", category=\"McPartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_redundantBucketsSize{$ClusterFilterLabel=\"$Cluster\", category=\"McPartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PartitionedRegionStats (Max)",
   "type": "table",
   "description": "$Cluster: PartitionedRegionStats - max values of all member stats per region",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max (gemfire_PartitionMessagesProcessed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_PartitionMessagesReceived{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_PartitionMessagesSent{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_actualRedundantCopies{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_applyReplicationCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_applyReplicationInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_applyReplicationTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketCreateTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketCreatesCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketCreatesFailed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketCreatesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketDestroyTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketDestroysCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketDestroysFailed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_bucketDestroysInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_configuredRedundantCopies{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_containsKeyCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_containsKeyOpsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_containsKeyRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_containsKeyTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_containsValueForKeyCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_containsValueForKeyTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_createOpsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_createRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_createTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_createsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_destroyOpsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_destroyRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_destroyTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_destroysCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_getEntryCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_getEntryTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_getOpsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_getRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_getTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_invalidateOpsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_invalidateRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_invalidateTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_invalidatesCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_localMaxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_lowRedundancyBucketCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_noCopiesBucketCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_partitionMessagesProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_prMetaDataSentCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_preferredReadLocal{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_preferredReadRemote{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryBucketCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryBucketsCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryBucketsSize{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryTransferTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryTransfersCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryTransfersFailed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_primaryTransfersInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putAllMsgsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putAllRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putAllTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putAllsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putLocalCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putLocalInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putLocalTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putOpsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putRemoteCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putRemoteInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putRemoteTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalanceBucketCreateTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalanceBucketCreatesCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalanceBucketCreatesFailed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalanceBucketCreatesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalancePrimaryTransferTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalancePrimaryTransfersCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalancePrimaryTransfersFailed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_rebalancePrimaryTransfersInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveriesCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveriesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_recoveryTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_redundantBucketsCount{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_redundantBucketsSize{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removeAllMsgsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removeAllRetries{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removeAllTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_removeAllsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_sendReplicationCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_sendReplicationInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_sendReplicationTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_totalNumBuckets{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringBecamePrimary{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringBecamePrimaryTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringClosed{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringClosedTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringOtherPrimary{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringOtherPrimaryTime{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (gemfire_volunteeringThreads{$ClusterFilterLabel=\"$Cluster\", category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}