{
 "title": "All Memory LRU",
 "tags": [
  "gemfire",
  "distribution",
  "eviction",
  "memory lru",
  "lru",
  "all memory lru"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory LRU Regions: Byte Count",
   "type": "barchart",
   "description": "Number of bytes in region.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_byteCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Destroys",
   "type": "barchart",
   "description": "Number of entry destroys triggered by LRU.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Byte Count",
   "type": "table",
   "description": "Number of bytes in region.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_byteCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Bytes Allowed",
   "type": "table",
   "description": "Total number of bytes allowed in this region.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_bytesAllowed{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Destroys",
   "type": "table",
   "description": "Number of entry destroys triggered by LRU.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Evaluations",
   "type": "table",
   "description": "Number of entries evaluated during LRU operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Evictions",
   "type": "table",
   "description": "Total number of entry evictions triggered by LRU.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvictions{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory LRU Regions: Greedy Returns",
   "type": "table",
   "description": "Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=~\"$ClusterList\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}