{
 "title": "All  Disk Stores Columns",
 "tags": [
  "all gemfire",
  "storage",
  "disk store"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Stores: Queue Size",
   "type": "table",
   "description": "Queue size",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queueSize{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Writes",
   "type": "table",
   "description": "Number of writes to disk store.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_writes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Written Bytes",
   "type": "table",
   "description": "Total amount of data written to data store.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_writtenBytes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Write Time",
   "type": "table",
   "description": "Write latency",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_writeTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Reads",
   "type": "table",
   "description": "Number of reads from disk store.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reads{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Read Bytes",
   "type": "table",
   "description": "Total amount of data read from data store.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_readBytes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Read Time",
   "type": "table",
   "description": "Read latency",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_readTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Flushes",
   "type": "table",
   "description": "Number of write flushes to disk store.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_flushes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Flushed Bytes",
   "type": "table",
   "description": "Total amount of data flushed to data store",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_flushedBytes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Flush Time",
   "type": "table",
   "description": "Flush latency",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_flushTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}