{
 "title": "All Async Queues",
 "tags": [
  "all gemfire",
  "async queue",
  "messaging"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Async Queues: Queue Size",
   "type": "timeseries",
   "description": "Number of events in the async queue.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Async Queues: Queue Count",
   "type": "timeseries",
   "description": "Number of  async queues.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Async Queues",
   "type": "table",
   "description": "Async queue stats",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncQueueAddTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueRemoveTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSizeExceeded{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueTimeoutExceeded{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueuedMsgs{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}