{
 "title": "Disk Stores Rows Charts",
 "tags": [
  "gemfire",
  "disk store"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Stores: Queue Size",
   "type": "barchart",
   "description": "$Cluster: Queue size",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Writes",
   "type": "barchart",
   "description": "$Cluster: Number of writes to disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_writes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Written Bytes",
   "type": "barchart",
   "description": "$Cluster: Total amount of data written to data store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_writtenBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Write Time",
   "type": "barchart",
   "description": "$Cluster: Write latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_writeTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Reads",
   "type": "barchart",
   "description": "$Cluster: Number of reads from disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_reads{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Read Bytes",
   "type": "barchart",
   "description": "$Cluster: Total amount of data read from data store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_readBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Read Time",
   "type": "barchart",
   "description": "$Cluster: Read latency",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_readTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Flushes",
   "type": "barchart",
   "description": "$Cluster: Number of write flushes to disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_flushes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Flushed Bytes",
   "type": "barchart",
   "description": "$Cluster: Total amount of data flushed to data store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_flushedBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Stores: Flush Time",
   "type": "barchart",
   "description": "$Cluster: Flush latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_flushTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}