{
 "title": "Dual TCP",
 "tags": [
  "dual gemfire",
  "distribution",
  "tcp",
  "dual tcp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: TCP: Messages Sent/Received Ratio",
   "type": "timeseries",
   "description": "$Cluster: Average ratio of number of messages sent and received per member.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_tcpMessagesSent{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}/gemfire_tcpMessagesReceived{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: TCP: Messages Sent/Received Ratio",
   "type": "timeseries",
   "description": "$Cluster2: Average ratio of number of messages sent and received per member.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_tcpMessagesSent{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}/gemfire_tcpMessagesReceived{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: TCP: Average Socket Write Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to write on socket per member.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}/gemfire_syncSocketWrites{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: TCP: Average Socket Write Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time took to write on socket per member.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}/gemfire_syncSocketWrites{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP: Average Socker Lock Time",
   "type": "timeseries",
   "description": "$Cluster: Average time to lock socket per member.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_socketLockTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}/gemfire_socketLocks{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: TCP: Average Socker Lock Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time to lock socket per member.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_socketLockTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}/gemfire_socketLocks{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP: Average Sync Socket Write Time",
   "type": "timeseries",
   "description": "$Cluster: Average time to synchronously write on socket per member.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}/gemfire_syncSocketWrites{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: TCP: Average Sync Socket Write Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time to synchronously write on socket per member.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}/gemfire_syncSocketWrites{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: TCP: Connection, Channel, Messages",
   "type": "table",
   "description": "$Cluster: TCP messaging stats",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_tcpAcquireConnectionPending{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsActivated{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsDeactivated{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsRegistered{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsUnregistered{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpConnectionGracefulCloses{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpConnectionUnexpectedCloses{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpDispatchRequestTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpDispatchRequestTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckRequestsSent{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckResponsesReceived{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckResponsesSent{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpMessagesReceived{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpMessagesSent{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: TCP: Connection, Channel, Messages",
   "type": "table",
   "description": "$Cluster2: TCP messaging stats",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_tcpAcquireConnectionPending{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsActivated{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsDeactivated{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsRegistered{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsUnregistered{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpConnectionGracefulCloses{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpConnectionUnexpectedCloses{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpDispatchRequestTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpDispatchRequestTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckRequestsSent{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckResponsesReceived{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckResponsesSent{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpMessagesReceived{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpMessagesSent{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: TCP: Async/Sync Socket",
   "type": "table",
   "description": "$Cluster: Async and sync socket stats",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncSocketWriteBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWriteRetries{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWriteTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWrites{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWritesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLockTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLocks{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLocksInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWriteBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWrites{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWritesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: TCP: Async/Sync Socket",
   "type": "table",
   "description": "$Cluster2: Async and sync socket stats",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncSocketWriteBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWriteRetries{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWriteTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWrites{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWritesInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLockTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLocks{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLocksInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWriteBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWrites{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWritesInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}