{
 "title": "Dual Async Queues",
 "tags": [
  "dual gemfire",
  "distribution",
  "dual async queues",
  "async queues"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Async Queues: Queue Size",
   "type": "timeseries",
   "description": "$Cluster: Number of events in the async queue.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Async Queues: Queue Size",
   "type": "timeseries",
   "description": "$Cluster2: Number of events in the async queue.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Async Queues: Queue Count",
   "type": "timeseries",
   "description": "$Cluster: Number of  async queues.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Async Queues: Queue Count",
   "type": "timeseries",
   "description": "$Cluster2: Number of  async queues.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Async Queues",
   "type": "table",
   "description": "$Cluster: Async queue stats",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncQueueAddTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueRemoveTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSizeExceeded{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueTimeoutExceeded{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueuedMsgs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Async Queues",
   "type": "table",
   "description": "$Cluster2: Async queue stats",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncQueueAddTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueRemoveTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSizeExceeded{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueTimeoutExceeded{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueuedMsgs{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}