{
 "title": "Dual Count LRU",
 "tags": [
  "dual gemfire",
  "count lru",
  "dual count lru",
  "distribution"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Count LRU Regions: LRU Destroys",
   "type": "barchart",
   "description": "$Cluster: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: LRU Destroys",
   "type": "barchart",
   "description": "$Cluster2: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Count LRU Regions: Entry Count",
   "type": "barchart",
   "description": "$Cluster: Number of entries in each region.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_entryCount{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: Entry Count",
   "type": "barchart",
   "description": "$Cluster2: Number of entries in each region.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_entryCount{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster:  Count LRU Regions: Entries Allowed",
   "type": "table",
   "description": "$Cluster: Number of entries allowed in this region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entriesAllowed{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2:  Count LRU Regions: Entries Allowed",
   "type": "table",
   "description": "$Cluster2: Number of entries allowed in this region.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entriesAllowed{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Count LRU Regions: Entry Count",
   "type": "table",
   "description": "$Cluster: Number of entries in this region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entryCount{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: Entry Count",
   "type": "table",
   "description": "$Cluster2: Number of entries in this region.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entryCount{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Count LRU Regions: LRU Destroys",
   "type": "table",
   "description": "$Cluster: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: LRU Destroys",
   "type": "table",
   "description": "$Cluster2: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Count LRU Regions: LRU Evaluations",
   "type": "table",
   "description": "$Cluster: Number of entries evaluated during LRU operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: LRU Evaluations",
   "type": "table",
   "description": "$Cluster2: Number of entries evaluated during LRU operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Count LRU Regions: LRU Evictions",
   "type": "table",
   "description": "$Cluster: Number of total entry evictions triggered by an LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: LRU Evictions",
   "type": "table",
   "description": "$Cluster2: Number of total entry evictions triggered by an LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Count LRU Regions: LRU Greedy Returns",
   "type": "table",
   "description": "$Cluster: Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=\"$Cluster\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Count LRU Regions: LRU Greedy Returns",
   "type": "table",
   "description": "$Cluster2: Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=\"$Cluster2\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}