{
 "title": "Dual Linux Systems",
 "tags": [
  "dual gemfire",
  "linux",
  "linux system"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Average CPU (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Linux System: Average CPU usage across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_cpuActive{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Active CPU"
    },
    {
     "expr": "avg(gemfire_cpuIdle{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Idle CPU"
    }
   ]
  },
  {
   "title": "$Cluster: Average Memory (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average system memory sizes across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "avg(gemfire_bufferMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Buffer"
    },
    {
     "expr": "avg(gemfire_cachedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(gemfire_sharedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Shared"
    },
    {
     "expr": "avg(gemfire_dirtyMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "avg(gemfire_rssSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"})",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "$Cluster: Average Allocated/Unallocated Swap (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average number of pages swapped across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Allocated Swap"
    },
    {
     "expr": "avg(gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Unallocated Swap"
    }
   ]
  },
  {
   "title": "$Cluster2: Average CPU (Aggregate)",
   "type": "piechart",
   "description": "$Cluster2: Linux System: Average CPU usage across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_cpuActive{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Active CPU"
    },
    {
     "expr": "avg(gemfire_cpuIdle{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Idle CPU"
    }
   ]
  },
  {
   "title": "$Cluster2: Average Memory (Aggregate)",
   "type": "piechart",
   "description": "$Cluster2: Average system memory sizes across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "avg(gemfire_bufferMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Buffer"
    },
    {
     "expr": "avg(gemfire_cachedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(gemfire_sharedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Shared"
    },
    {
     "expr": "avg(gemfire_dirtyMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "avg(gemfire_rssSize{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxProcessStats\"})",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "$Cluster2: Average Allocated/Unallocated Swap (Aggregate)",
   "type": "piechart",
   "description": "$Cluster2: Average number of pages swapped across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Allocated Swap"
    },
    {
     "expr": "avg(gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Unallocated Swap"
    }
   ]
  },
  {
   "title": "$Cluster: Average Disk Operations (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average CPU usage across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_diskBytesRead{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "avg(gemfire_diskBytesWritten{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  {
   "title": "$Cluster: Average Swaped In/Out (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average number of pages swapped in and out across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Swapped In"
    },
    {
     "expr": "avg(gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Swapped Out"
    }
   ]
  },
  {
   "title": "$Cluster: Average Paged In/Out (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average number of pages in and out across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Paged In"
    },
    {
     "expr": "avg(gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Paged Out"
    }
   ]
  },
  {
   "title": "$Cluster2: Average Disk Operations (Aggregate)",
   "type": "piechart",
   "description": "$Cluster2: Average CPU usage across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_diskBytesRead{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "avg(gemfire_diskBytesWritten{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  {
   "title": "$Cluster2: Average Swaped In/Out (Aggregate)",
   "type": "piechart",
   "description": "$Cluster2: Average number of pages swapped in and out across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Swapped In"
    },
    {
     "expr": "avg(gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Swapped Out"
    }
   ]
  },
  {
   "title": "$Cluster2: Average Paged In/Out (Aggregate)",
   "type": "piechart",
   "description": "$Cluster2: Average number of pages in and out across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Paged In"
    },
    {
     "expr": "avg(gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Paged Out"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Memory",
   "type": "table",
   "description": "$Cluster2: Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_physicalMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_bufferMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cachedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sharedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_dirtyMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_rssSize{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Memory",
   "type": "table",
   "description": "$Cluster2: Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_physicalMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_bufferMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cachedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sharedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_dirtyMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_rssSize{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux TCP",
   "type": "table",
   "description": "$Cluster: TCP transmission statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_tcpExtListenDrops{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtListenOverflows{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtSynCookiesRecv{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtSynCookiesSent{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpRetransSegs{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_soMaxConn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux TCP",
   "type": "table",
   "description": "$Cluster2: TCP transmission statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_tcpExtListenDrops{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtListenOverflows{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtSynCookiesRecv{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtSynCookiesSent{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpRetransSegs{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_soMaxConn{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux Network Transmisson",
   "type": "table",
   "description": "$Cluster: Network related stats for transmitted (xmit) traffic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_xmitBytes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitCollisions{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitDrops{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitErrors{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitPackets{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loopbackBytes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loopbackPackets{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Network Transmisson",
   "type": "table",
   "description": "$Cluster2: Network related stats for transmitted (xmit) traffic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_xmitBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitCollisions{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitDrops{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitErrors{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitPackets{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loopbackBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loopbackPackets{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux Network Received",
   "type": "table",
   "description": "$Cluster: Network related stats for received (recv) traffic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_recvBytes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvDrops{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvErrors{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvPackets{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Network Received",
   "type": "table",
   "description": "$Cluster2: Network related stats for received (recv) traffic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_recvBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvDrops{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvErrors{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvPackets{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux CPU",
   "type": "table",
   "description": "$Cluster: CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_cpuActive{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuIdle{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuNice{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuNonUser{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuSteal{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuSystem{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuUser{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpus{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux CPU",
   "type": "table",
   "description": "$Cluster2: CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_cpuActive{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuIdle{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuNice{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuNonUser{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuSteal{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuSystem{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuUser{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpus{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux Average System Load",
   "type": "table",
   "description": "$Cluster: Average system load in 1, 5 and 15 min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_loadAverage1{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadAverage5{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadAverage15{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Average System Load",
   "type": "table",
   "description": "$Cluster2: Average system load in 1, 5 and 15 min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_loadAverage1{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadAverage5{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadAverage15{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux Disk Operations",
   "type": "table",
   "description": "$Cluster: Disk operation statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_diskBytesRead{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskBytesWritten{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskOpsInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskReadsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskReadsMerged{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTime{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeReading{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeWriting{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskWritesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskWritesMerged{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Disk Operations",
   "type": "table",
   "description": "$Cluster2: Disk operation statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_diskBytesRead{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskBytesWritten{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskOpsInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskReadsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskReadsMerged{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTime{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeReading{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeWriting{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskWritesCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskWritesMerged{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux Virtual Memory Pages",
   "type": "table",
   "description": "$Cluster: Virtual memory page statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Virtual Memory Pages",
   "type": "table",
   "description": "$Cluster2: Virtual memory page statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux Processes",
   "type": "table",
   "description": "$Cluster: Process related statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_imageSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_rssSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processCreates{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_contextSwitches{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux Processes",
   "type": "table",
   "description": "$Cluster:2 Process related statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_imageSize{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_rssSize{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processCreates{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processes{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_contextSwitches{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Linux I/O",
   "type": "table",
   "description": "$Cluster: I/O related statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_iowait{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_irq{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_softirq{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Linux I/O",
   "type": "table",
   "description": "$Cluster2: I/O related statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_iowait{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_irq{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_softirq{$ClusterFilterLabel=\"$Cluster2\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}