{
 "title": "Locators",
 "tags": [
  "gemfire",
  "cluster",
  "locator"
 ],
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "LocatorCluster",
    "label": "LocatorCluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$LocatorCluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locator Count",
   "type": "stat",
   "description": "$Cluster: Number of locators",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gemfire_locators{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Conn Requests",
   "type": "stat",
   "description": "$Cluster: Highest number of client connection requests",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Conn Request Time",
   "type": "stat",
   "description": "$Cluster: Highest client connection request time",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "description": "$Cluster:Highest number of locator requests in progress",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_requestsInProgress{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Conn Response Failures",
   "type": "stat",
   "description": "$Cluster: Highest number of client connection response failures",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients",
   "type": "table",
   "description": "$LocatorCluster: Client connections and activities overview",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators Resources",
   "type": "table",
   "description": "$Cluster: Locator resource stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$LocatorCluster\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$LocatorCluster\",category=\"VMStats\",exported_instance=\"vmStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$LocatorCluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"ParNew\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"ConcurrentMarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"PS Scavenge\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"PS MarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"G1 Young Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$LocatorCluster\",exported_instance=\"G1 Old Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Client Connection",
   "type": "table",
   "description": "$Cluster: Client connection request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Client Replacement",
   "type": "table",
   "description": "$Cluster: Client replacement request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Find Coordinator",
   "type": "table",
   "description": "$Cluster: Find coordinator request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_findCoordinatorRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Get All Servers",
   "type": "table",
   "description": "$Cluster: Get all servers request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getAllServersRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Get View",
   "type": "table",
   "description": "$Cluster: Get view request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getViewRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Locator List",
   "type": "table",
   "description": "$Cluster: Locator list request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorListRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Locator Status",
   "type": "table",
   "description": "$Cluster: Locator status request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorStatusRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Queue Connection",
   "type": "table",
   "description": "$Cluster: Queue connection request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queueConnectionRequestFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequests{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailures{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponses{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Processing, Servers, Locators",
   "type": "table",
   "description": "$Cluster: Request and response processing time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_requestProcessingFailureTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestProcessingTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestsInProgress{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingFailureTime{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingTime{$ClusterFilterLabel=\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_serverLoadUpdates{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_servers{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}