{
 "title": "Off-Heap",
 "tags": [
  "gemfire",
  "distribution",
  "off-heap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Off-Heap: Free, Used (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Off-Heap: Object Count (Aggregate)",
   "type": "stat",
   "description": "$Cluster: The number of objects currently stored in off-heap memory.",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_objects{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Off-Heap: Used, Free, Max (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all members' free, used, and max off-heap.",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"})",
     "legendFormat": "Free Off-Heap"
    },
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"})",
     "legendFormat": "Used Off-eap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"})",
     "legendFormat": "Max Off-Heap"
    }
   ]
  },
  {
   "title": "Off-Heap: Memory",
   "type": "table",
   "description": "$Cluster: Off-heap memory stats per member.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_defragmentationTime{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_defragmentations{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_defragmentationsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fragmentation{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fragments{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_freedChunks{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_largestFragment{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_objects{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_reads{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}