{
 "title": "System Resources",
 "tags": [
  "gemfire",
  "resources",
  "memory",
  "os",
  "jvm",
  "performance",
  "latency",
  "throughput"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "$Cluster: Number of running data nodes in the cluster excluding locators",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_nodes{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "$Cluster: Member resource statuses",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ParNew\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ConcurrentMarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS Scavenge\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS MarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Old Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Heap Memory: Free, Used (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Regions: Entries",
   "type": "stat",
   "description": "$Cluster: Number of entries per region in descending order. Displays up to top 15 regions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Aggregates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": " Heap: Used, Free, Max (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Heap: Committed Memory (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member committed heap memories",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\",area=\"heap\",id=\"CMS Old Gen\"})",
     "legendFormat": "CMS Old Gen"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"Par Eden Space\"})",
     "legendFormat": "Par Eden Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"Par Survivor Space\"})",
     "legendFormat": "Par Survivor Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"G1 Eden Space\"})",
     "legendFormat": "G1 Eden Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"G1 Survivor Space\"})",
     "legendFormat": "G1 Survivor Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"G1 Old Gen\"})",
     "legendFormat": "G1 Old Gen"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"PS Eden Space\"})",
     "legendFormat": "PS Eden Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"PS Survivor Space\"})",
     "legendFormat": "PS Eden Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"heap\", id=\"PS Old Gen\"})",
     "legendFormat": "PS Old Gen"
    }
   ]
  },
  {
   "title": "Non-Heap: Used, Free, Max (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Non-heap memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmNonHeapMemoryStats\"} - gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Non-Heap: Committed Memory (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member committed non-heap memories",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"nonheap\", id=\"Metaspace\"})",
     "legendFormat": "Metaspace"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"nonheap\", id=\"Compressed Class Space\"})",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"nonheap\", id=\"Code Cache\"})",
     "legendFormat": "Code Cache"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"nonheap\", id=\"CodeHeap 'non-nmethods'\"})",
     "legendFormat": "CodeHeap 'non-nmethods'"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"nonheap\", id=\"CodeHeap 'non-profiled nmethods'\"})",
     "legendFormat": "CodeHeap 'non-profiled nmethods'"
    },
    {
     "expr": "sum(gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\", area=\"nonheap\", id=\"CodeHeap 'profiled nmethods'\"})",
     "legendFormat": "CodeHeap 'profiled nmethods'"
    }
   ]
  },
  {
   "title": "OffHeap Memory (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member off-heap memories",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_offHeapUsedMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gemfire_offHeapFreeMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gemfire_offHeapMaxMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max GC Count (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: GC counts of the member with the highest value",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"})",
     "legendFormat": "ZGC Cycles"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"})",
     "legendFormat": "ZGC Pauses"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ParNew\"})",
     "legendFormat": "Minor GC (ParNew)"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ConcurrentMarkSweep\"})",
     "legendFormat": "Major GC (ConcurrentSweep)"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS Scavenge\"})",
     "legendFormat": "Major GC (PS Scavenge)"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS MarkSweep\"})",
     "legendFormat": "Major GC (PS MarkSweep)"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Young Generation\"})",
     "legendFormat": "Major GC (G1 Young Generation)"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Old Generation\"})",
     "legendFormat": "Major GC (G1 Old Generation)"
    }
   ]
  },
  {
   "title": "Thread Count (Aggregate)",
   "type": "barchart",
   "description": "$Cluster: Thread count of each member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_daemonThreads{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"})",
     "legendFormat": "{{instance}} Daemon"
    },
    {
     "expr": "sum(gemfire_jvm_threads_live_threads{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Live"
    },
    {
     "expr": "sum(gemfire_jvm_threads_peak_threads{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Peak"
    },
    {
     "expr": "sum(gemfire_threads{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"})",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "sum(gemfire_threadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"})",
     "legendFormat": "{{instance}} Starts"
    }
   ]
  },
  {
   "title": "Thread State (Aggregate)",
   "type": "barchart",
   "description": "$Cluster: Thread count of each member",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"new\"})",
     "legendFormat": "{{instance}} New"
    },
    {
     "expr": "sum(gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"blocked\"})",
     "legendFormat": "{{instance}} Blocked"
    },
    {
     "expr": "sum(gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"runnable\"})",
     "legendFormat": "{{instance}} Runnable"
    },
    {
     "expr": "sum(gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"terminated\"})",
     "legendFormat": "{{instance}} Terminated"
    },
    {
     "expr": "sum(gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"timed-waiting\"})",
     "legendFormat": "{{instance}} Timed-Waiting"
    },
    {
     "expr": "sum(gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"waiting\"})",
     "legendFormat": "{{instance}} Waiting"
    }
   ]
  },
  {
   "title": "Linux Total Swap Space (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Swap space size of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"})",
     "legendFormat": "{{instance}} Allocated Swap"
    },
    {
     "expr": "sum(gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"})",
     "legendFormat": "{{instance}} Unallocated Swap"
    }
   ]
  },
  {
   "title": "Memory Partitioned Regions (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member owned partitioned region memory.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"})",
     "legendFormat": "Partitioned Region Memory"
    }
   ]
  },
  { "title": "Per Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Free Memory (Per Member)",
   "type": "piechart",
   "description": "$Cluster: Free memory per member",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\"}-gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory (Per Member)",
   "type": "piechart",
   "description": "$Cluster: Used memory per member",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System CPU Load (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: System CPU load of each member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Heap memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"} - gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Used Heap (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Used heap memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Heap: Used, Free, Max (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Non-heap memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmNonHeapMemoryStats\"} - gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Off-Heap (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Used off-heap memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Count (Per Member)",
   "type": "barchart",
   "description": "$Cluster: Thread count of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_daemonThreads{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"}",
     "legendFormat": "{{instance}} Daemon"
    },
    {
     "expr": "gemfire_jvm_threads_live_threads{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Live"
    },
    {
     "expr": "gemfire_jvm_threads_peak_threads{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Peak"
    },
    {
     "expr": "gemfire_threads{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"}",
     "legendFormat": "{{instance}} Total"
    },
    {
     "expr": "gemfire_threadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"}",
     "legendFormat": "{{instance}} Starts"
    }
   ]
  },
  {
   "title": "Thread State (Per Member)",
   "type": "barchart",
   "description": "$Cluster: Thread count of each member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"new\"}",
     "legendFormat": "{{instance}} New"
    },
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"blocked\"}",
     "legendFormat": "{{instance}} Blocked"
    },
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"runnable\"}",
     "legendFormat": "{{instance}} Runnable"
    },
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"terminated\"}",
     "legendFormat": "{{instance}} Terminated"
    },
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"timed-waiting\"}",
     "legendFormat": "{{instance}} Timed-Waiting"
    },
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\", state=\"waiting\"}",
     "legendFormat": "{{instance}} Waiting"
    }
   ]
  },
  {
   "title": "GC Count (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: GC counts of the member with the highest value",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "{{instance}}  ZGC Cycles"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "{{instance}} ZGC Pauses"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ParNew\"}",
     "legendFormat": "{{instance}} Minor GC (ParNew)"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ConcurrentMarkSweep\"}",
     "legendFormat": "{{instance}} Major GC (ConcurrentSweep)"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS Scavenge\"}",
     "legendFormat": "{{instance}} Major GC (PS Scavenge)"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS MarkSweep\"}",
     "legendFormat": "{{instance}} Major GC (PS MarkSweep)"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Young Generation\"}",
     "legendFormat": "{{instance}} Major GC (G1 Young Generation)"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Old Generation\"}",
     "legendFormat": "{{instance}} Major GC (G1 Old Generation)"
    }
   ]
  },
  {
   "title": "File Descriptors (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Number of open and max file descriptors per member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_fdsOpen{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"}",
     "legendFormat": "{{instance}} Open"
    },
    {
     "expr": "gemfire_fdLimit{$ClusterFilterLabel=\"$Cluster\", category=\"VMStats\"}",
     "legendFormat": "{{instance}} Limit"
    }
   ]
  },
  {
   "title": "Linux Swap Space (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Swap space size of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"}",
     "legendFormat": "{{instance}} Allocated Swap"
    },
    {
     "expr": "gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"}",
     "legendFormat": "{{instance}} Unallocated Swap"
    }
   ]
  },
  {
   "title": "Linux Pages (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Paged in and out on each member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"}",
     "legendFormat": "{{instance}} Paged In"
    },
    {
     "expr": "gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"}",
     "legendFormat": "{{instance}} Paged Out"
    }
   ]
  },
  {
   "title": "Linux Pages Swapped (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Pages swapped in and out on each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"}",
     "legendFormat": "{{instance}} Swapped In"
    },
    {
     "expr": "gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\", category=\"LinuxSystemStats\"}",
     "legendFormat": "{{instance}} Swapped Out"
    }
   ]
  }
 ]
}