{
 "title": "00Main",
 "tags": [
  "gemfire",
  "main"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main Dashboard",
   "type": "text",
   "description": "The main dashboard of PadoGrid GemFire Dashboards (PHD) that resembles the main dashboard of GemFire Management Center (HMC). PHD includes additional metrics that are not available in HMC and vice versa. PHD exposes a finer degree of individual metric details along with federated cluster views making it more suitable for monitoring production systems.",
   "gridPos": { "h": 42, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "## Main\n\n- [Main Dashboard](/d/ed5d1905-d13d-446a-83d5-3d33d3aadddc/00main?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Dual Main Dashboard](/d/2f6503d9-5b23-4af6-9a87-08f799229df5/00dual-main?var-DataSource=$DataSource&var-Cluster=$Cluster&var-Cluster2=$Cluster2&${__url_time_range})\n- [All Main Dashboard](/d/5a076038-1d97-4c44-abe7-26020351d90b/00main-all?${__url_time_range})\n\n## Cluster\n\n- [Clients](/d/640ccb83-dda1-4413-a077-7ccb5149378f/clients?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Members](/d/b02dcbcb-af7b-4708-a8ef-d1e226807a3b/members?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Locators](/d/fe5quiw68bev4d/locators?var-DataSource=$DataSource&${__url_time_range})\n- [WAN Replication](/d/dd910e07-3550-4d12-9bd4-7aa0fb11881e/wan?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Storage\n\n- [Partitioned Regions](/d/fef86fcb-3669-4128-b36f-ffa9fd0b8f84/partitioned-regions-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Column Charts](/d/72e26aea-f380-42a3-bba0-4241fa23cb2b/partitioned-regions-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Colum Tables](/d/40a5bd69-7869-4ec9-8b91-309b0c83a5c4/partitioned-regions-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Row Charts](/d/529c1c7f-b4c6-459a-a0d9-e90ab7af0ce2/partitioned-regions-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Row Tables](/d/fef86fcb-3669-4128-b36f-ffa9fd0b8f84/partitioned-regions-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Query Charts](/d/04b11f95-99ca-47e8-b1e2-451cbd2bfdb2/partitioned-regions-query-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Query Tables](/d/51a30a7d-7b18-4f5a-b8e7-b6cd6ffa0c42/partitioned-regions-query-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Replicated/Local Regions](/d/6627cd85-7338-4202-87fd-e83859821fa3/replicated-region-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Column Charts](/d/f18d178b-20ea-4b80-afb3-43b8db14f37e/replicated-regions-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Column Tables](/d/b4d04c6a-5baf-42ed-8571-f538cccfb9fd/replicated-regions-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Row Charts](/d/8435fa7b-226b-4dec-aa1e-7f5943742318/replicated-regions-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Row Tables](/d/6627cd85-7338-4202-87fd-e83859821fa3/replicated-regions-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Disk Regions](/d/de9edphrk8s1sb/disk-regions-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Column Charts](/d/de9er8pny835se/disk-regions-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Column Tables](/d/fe9eqr4dggx6oe/disk-regions-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Row Charts](/d/ee9eohy4stce8a/disk-regions-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Row Tables](/d/de9edphrk8s1sb/disk-regions-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Disk Stores](/d/f843bff3-4d6e-4319-aa5b-5ab91167be6f/disk-stores-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Column Charts](/d/52c2d482-86de-448e-8b5d-e69f1d14b3d4/disk-stores-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Column Tables](/d/78623c23-2974-4046-9c46-05d1441cb9ba/disk-stores-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Row Charts](/d/335deba8-3642-40ef-8b1c-cfec47d4e579/disk-stores-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Row Tables](/d/f843bff3-4d6e-4319-aa5b-5ab91167be6f/disk-stores-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Compute\n\n- [Functions](/d/bd5da1ca-3f7b-4f24-84f3-5b4e861e6774/functions?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Indexes](/d/de026a4a-1864-4348-bdb7-05319d4f5a9a/indexes?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [CQ](/d/ae9bvg0fdrls0b/cq?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Search](/d/cea9gf0l4uuwwb/search-lucene?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Distribution\n\n- [Partitions](/d/a2d1d20f-7330-48b4-9d84-3cb9ecfd172a/partitions?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Async Queues](/d/e314f400-1052-4549-85c8-b9935a97dad7/async-queues?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Count LRU](/d/ae9oxe8j3wu80c/count-lru?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Heap LRU](/d/fe9iqo04g3y80b/heap-lru?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Memory LRU](/d/ce9ium8hhkv7kd/memory-lru?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Off-Heap](/d/fe9ouhl98v0g0b/off-heap?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [PDX](/d/67561ce2-cb55-4f44-8881-fed93a225b4d/pdx?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Distributed Locks](/d/17c5eb71-106f-41ef-9e0c-9ff69d2491c9/distributed-locks?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [TCP](/d/df3c92d1-33b4-4c53-8218-ce8f460b6061/tcp?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Linux\n\n- [Linux System](/d/047f767d-329e-4b08-a376-9a366c944e0e/linux-system?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Generated\n\n- [Category Stats](/d/db7ee8c2-12cf-4d39-b593-f7c2b8163c76/gemfire-category-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Category Region Stats](/d/ad2e81ff-f283-401e-b693-93c3ba7c59ca/gemfire-category-region-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [NonCategory Stats](/d/96a048d8-9517-41d2-aff3-824fc43c2102/gemfire-noncategory-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Partitioned Regions Column Tables](/d/c1550422-0fd3-4950-b9f1-1c2b5352a426/gemfire-partitioned-regions-columns-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Replicated/Local Regions Column Tables](/d/b6f719fc-e9ea-4dd5-9635-aed95188900c/gemfire-replicated-regions-columns-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Member Regions Column Tables](/d/92d76020-1dce-4ca2-b32d-8a309950847c/gemfire-member-regions-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n"
   }
  },
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Count (Servers)",
   "type": "stat",
   "description": "$Cluster: Number of running data nodes in the cluster excluding locators",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_nodes{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Heap Memory: Free, Used (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Regions: Entries",
   "type": "stat",
   "description": "$Cluster: Number of entries per region in descending order. Displays up to top 15 regions.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Reads per second",
   "type": "stat",
   "description": "$Cluster: Aggregated get() rate across the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"} / (gemfire_getTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locator Count",
   "type": "stat",
   "description": "$Cluster: Number of locators",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster\",category=\"LocatorStats\",member_type=\"locator\"} and on() (gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster\",category=\"LocatorStats\",member_type=\"locator\"} >= 0)) or on() gemfire_locators{$ClusterFilterLabel=\"$Cluster\",category=\"LocatorStats\",member_type=\"locator\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries (Primary & Backup)",
   "type": "stat",
   "description": "$Cluster: Total number of entries in all regions including primary and backup",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Total Operations",
   "type": "stat",
   "description": "$Cluster: Sum of put(), get(), destroy(), putAll(), and removeAll() calls completed.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_putsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_destroysCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_putAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_removeAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Partitioned Region Entries",
   "type": "table",
   "description": "$Cluster: Number of primary entries in partitioned regions.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 11, "w": 11, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Other Region Entries",
   "type": "table",
   "description": "$Cluster: Number of highest entries in replicated and local regions.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "$Cluster: Member resource statuses",
   "gridPos": { "h": 17, "w": 21, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ParNew\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ConcurrentMarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS Scavenge\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS MarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Old Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}