{
 "title": "Clients",
 "tags": [
  "gemfire",
  "cluster",
  "client"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "description": "$Cluster: Number of client virtual machines (clients) connected.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Threads",
   "type": "timeseries",
   "description": "$Cluster: The current number of threads dealing with a client connection and the total number of threads created (starts) to deal with a client connection.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}} Threads"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}} Thread Starts"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Client Notifier",
   "type": "table",
   "description": "$Cluster: Statistics regarding cache server operations sent to all clients.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_durableReconnectionCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_events{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsEnqueuedWhileClientAwayCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueDroppedCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}