{
 "title": "Linux System",
 "tags": [
  "gemfire",
  "linux",
  "linux system",
  "os"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average CPU usage across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_cpuActive{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Active CPU"
    },
    {
     "expr": "avg(gemfire_cpuIdle{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Idle CPU"
    }
   ]
  },
  {
   "title": "Average Memory (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average system memory sizes across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "avg(gemfire_bufferMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Buffer"
    },
    {
     "expr": "avg(gemfire_cachedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(gemfire_sharedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Shared"
    },
    {
     "expr": "avg(gemfire_dirtyMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Dirty"
    },
    {
     "expr": "avg(gemfire_rssSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"})",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Average Allocated/Unallocated Swap (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average number of pages swapped across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Allocated Swap"
    },
    {
     "expr": "avg(gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Unallocated Swap"
    }
   ]
  },
  {
   "title": "Average Swaped In/Out (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average number of pages swapped in and out across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Swapped In"
    },
    {
     "expr": "avg(gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Swapped Out"
    }
   ]
  },
  {
   "title": "Average Paged In/Out (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average number of pages in and out across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Paged In"
    },
    {
     "expr": "avg(gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Paged Out"
    }
   ]
  },
  {
   "title": "Average Disk Operations (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Average CPU usage across all servers.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gemfire_diskBytesRead{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "avg(gemfire_diskBytesWritten{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"})",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  {
   "title": "Linux Memory",
   "type": "table",
   "description": "$Cluster: Memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_physicalMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_bufferMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cachedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sharedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_dirtyMemory{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_rssSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_allocatedSwap{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unallocatedSwap{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux TCP",
   "type": "table",
   "description": "$Cluster: TCP transmission statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_tcpExtListenDrops{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtListenOverflows{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtSynCookiesRecv{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpExtSynCookiesSent{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpRetransSegs{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_soMaxConn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux Network Transmisson",
   "type": "table",
   "description": "$Cluster: Network related stats for transmitted (xmit) traffic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_xmitBytes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitCollisions{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitDrops{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitErrors{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_xmitPackets{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loopbackBytes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loopbackPackets{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux Network Received",
   "type": "table",
   "description": "$Cluster: Network related stats for received (recv) traffic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_recvBytes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvDrops{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvErrors{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_recvPackets{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux CPU",
   "type": "table",
   "description": "$Cluster: CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_cpuActive{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuIdle{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuNice{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuNonUser{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuSteal{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuSystem{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpuUser{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cpus{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux Average System Load",
   "type": "table",
   "description": "$Cluster: Average system load in 1, 5 and 15 min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gemfire_loadAverage1{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadAverage5{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadAverage15{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux Disk Operations",
   "type": "table",
   "description": "$Cluster: Disk operation statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_diskBytesRead{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskBytesWritten{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskOpsInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskReadsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskReadsMerged{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTime{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeReading{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskTimeWriting{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskWritesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_diskWritesMerged{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux Virtual Memory Pages",
   "type": "table",
   "description": "$Cluster: Virtual memory page statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux Processes",
   "type": "table",
   "description": "$Cluster: Process related statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_imageSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_rssSize{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxProcessStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processCreates{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processes{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_contextSwitches{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linux I/O",
   "type": "table",
   "description": "$Cluster: I/O related statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_iowait{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_irq{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_softirq{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}