{
 "title": "Member",
 "tags": [
  "gemfire",
  "member",
  "single"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "Member",
    "query": {
     "query": "label_values(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Member" },
  {
   "title": "GemFire Cluster Member",
   "type": "text",
   "description": "Name of member clustered in $Cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "# ${Member}" }
  },
  {
   "title": "Memory: Free, Used",
   "type": "piechart",
   "description": "$Member: free vs. used memory",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Member Resources",
   "type": "table",
   "description": "$Member: Member resource overview",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ParNew\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ConcurrentMarkSweep\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS Scavenge\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS MarkSweep\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Young Generation\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Old Generation\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Member Up Time",
   "type": "stat",
   "description": "Member up time",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "$Member: Member system CPU usage with the threshold set at 90%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "$Member: Member threads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_threads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "gemfire_partitionedRegionThreads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Partitioned Region"
    },
    {
     "expr": "gemfire_longRunningThreads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Long Running"
    },
    {
     "expr": "gemfire_peakThreads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "gemfire_numThreadsStuck{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Stuck"
    }
   ]
  },
  {
   "title": "Used Heap and Thresholds",
   "type": "timeseries",
   "description": "$Member: Used heap, eviction threshold, critical threshold, and max heap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\", instance=\"$Member\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "gemfire_evictionThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Threshold"
    },
    {
     "expr": "gemfire_criticalThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical Threshold"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "Max Heap Threshold"
    }
   ]
  },
  {
   "title": "GC Count: Pauses, Cycles",
   "type": "timeseries",
   "description": "$Member: Member ZGC pause and cycle count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\", instance=\"$Member\"}",
     "legendFormat": "GC Minor Count"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\", instance=\"$Member\"}",
     "legendFormat": "GC Major Count"
    }
   ]
  },
  {
   "title": "Swapped Pages",
   "type": "timeseries",
   "description": "$Member: Total number of swap pages that have been read in from disk by the operating system’s memory manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Swapped In"
    },
    {
     "expr": "gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Swapped Out"
    }
   ]
  },
  {
   "title": "Page Count",
   "type": "timeseries",
   "description": "$Member: Total number of pages that have been brought into memory from disk by the operating system’s memory manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Page In"
    },
    {
     "expr": "gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Heap Events",
   "type": "timeseries",
   "description": "$Member: Heap events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_heapSafeEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Safe"
    },
    {
     "expr": "gemfire_evictionStartEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction"
    },
    {
     "expr": "gemfire_evictionStopEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Stop"
    },
    {
     "expr": "gemfire_heapCriticalEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Used NonHeap",
   "type": "timeseries",
   "description": "$Member: Used non-heap memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Off-Heap Thresholds",
   "type": "timeseries",
   "description": "$Member: Off-heap thresholds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_offHeapEvictionThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Threshold"
    },
    {
     "expr": "gemfire_offHeapCriticalThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical Threshold"
    }
   ]
  },
  {
   "title": "Off-Heap Events",
   "type": "timeseries",
   "description": "$Member: Off-heap events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_offHeapSafeEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Safe"
    },
    {
     "expr": "gemfire_offHeapEvictionStartEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction"
    },
    {
     "expr": "gemfire_offHeapEvictionStopEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Stop"
    },
    {
     "expr": "gemfire_offHeapCriticalEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Partitioned Regions",
   "type": "table",
   "description": "All partitioned regions in $Member sorted by descending order of entries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Regions",
   "type": "table",
   "description": "All replicated regions in $Member sorted by descending order of entries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Normal (Local) Regions",
   "type": "table",
   "description": "All normal (local) regions in $Member sorted by descending order of entries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Structures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Partitioned Regions: Primary Bucket Count",
   "type": "bargauge",
   "description": "$Cluster: Number of primary buckets in this member. Sorted in descending order.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(gemfire_primaryBucketCount{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Backup Bucket Count",
   "type": "bargauge",
   "description": "$Cluster: Total number of redundant buckets in this member. Sorted in descending order.",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(gemfire_bucketCount{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"}-gemfire_primaryBucketCount{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Actual Redundant Copies",
   "type": "timeseries",
   "description": "$Cluster: The least current redundant number of copies for any data in this partitioned region (there may be some data that is fully redundant, but some data will have only this number of copies). This value may drop when a data store is lost or rise when a data store is added. This value may drop temporarily during partitioned region creation or destruction and then rise again.\n\n✏️ If this value remains low, then partitioned region data is at risk and may be lost if another data store is lost.\n\nA healthy partitioned region will maintain a value equal to configuredRedundantCopies. The user should add one or more data stores if the value remains low. High- availability may result in a brief fluctuation, but it should return to a value equal to configuredRedundantCopies if there are sufficient data stores present (that is, terminating one data store will cause its data to fail over to another data store).",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "gemfire_actualRedundantCopies{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Low Redundancy Bucket Count",
   "type": "timeseries",
   "description": "$Cluster: The number of buckets in this partitioned region that currently have fewer copies than the configuredRedundantCopies. This value may rise above zero when a data store is lost and return to zero when one or more data stores are added. This value may rise temporarily during partitioned region creation or destruction and then return to zero.\n\n✏️ If this value remains above zero, then partitioned region data is at risk and may be lost if another data store is lost.\n\nThis value will be above zero whenever actualRedundantCopies is less than configuredRedundantCopies. A healthy partitioned region will maintain a value of zero. The user should add one or more datstores if this value remains above zero. High- availability may result in a brief fluctuation, but it should return to zero if there are sufficient data stores present (that is, terminating one data store will cause its data to fail over to another data store).\n\nA healthy partitioned region will maintain a value equal to configuredRedundantCopies. The user should add one or more data stores if the value remains low. High- availability may result in a brief fluctuation, but it should return to a value equal to configuredRedundantCopies if there are sufficient data stores present (that is, terminating one data store will cause its data to fail over to another data store).",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "gemfire_lowRedundancyBucketCount{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Configured Parameters",
   "type": "table",
   "description": "$Cluster: Total number of buckets and redundant copies. This value remains unchanged for a given partitioned region. Sorted by partitioned region name",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_totalNumBuckets{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "gemfire_configuredRedundantCopies{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "gemfire_localMaxMemory{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}