{
 "title": "PDX",
 "tags": [
  "gemfire",
  "pdx",
  "distribution"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PDX: Deserializations",
   "type": "timeseries",
   "description": "$Cluster: Number of PDX deserializations performed per member.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_pdxDeserializations{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PDX: Deserialized Bytes",
   "type": "timeseries",
   "description": "$Cluster: Amount of PDX deserialized data per member.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_pdxDeserializedBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PDX Stats",
   "type": "table",
   "description": "$Cluster: PDX stats",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pdxDeserializations{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pdxDeserializedBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pdxInstanceCreations{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pdxInstanceDeserializationTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pdxInstanceDeserializations{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pdxSerializations{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_pdxSerializedBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDX Type Registion: Peer",
   "type": "table",
   "description": "$Cluster: PDX peer type registration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_enumCreated{$ClusterFilterLabel=\"$Cluster\", category=\"PdxTypeRegistration\", exported_instance=\"PeerTypeRegistration\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_enumDefined{$ClusterFilterLabel=\"$Cluster\", category=\"PdxTypeRegistration\", exported_instance=\"PeerTypeRegistration\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_size{$ClusterFilterLabel=\"$Cluster\", category=\"PdxTypeRegistration\", exported_instance=\"PeerTypeRegistration\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_typeCreated{$ClusterFilterLabel=\"$Cluster\", category=\"PdxTypeRegistration\", exported_instance=\"PeerTypeRegistration\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_typeDefined{$ClusterFilterLabel=\"$Cluster\", category=\"PdxTypeRegistration\", exported_instance=\"PeerTypeRegistration\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}