{
 "title": "Search Lucene",
 "tags": [
  "gemfire",
  "compute",
  "lucene"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lucene Indexes: Average Query Execution Time",
   "type": "timeseries",
   "description": "$Cluster: Average Lucene query execution latency.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}/gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Executions",
   "type": "table",
   "description": "$Cluster: The number of Lucene queries executed on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Execution Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent executing Lucene queries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Execution Total Hits",
   "type": "table",
   "description": "$Cluster: The total number of documents returned by query executions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTotalHits{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Executions In Progress",
   "type": "table",
   "description": "$Cluster: The number of query executions currently in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Commit Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent in Lucene index commits.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_commitTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Commits",
   "type": "table",
   "description": "$Cluster: The number of Lucene index commits on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commits{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Commits In Progress",
   "type": "table",
   "description": "$Cluster: The number of Lucene index commits in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commitsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Documents",
   "type": "table",
   "description": "$Cluster: The number of documents in the index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_documents{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Failed Entries",
   "type": "table",
   "description": "$Cluster: The number of failed entries for the index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_failedEntries{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindex Repositories",
   "type": "table",
   "description": "$Cluster: The number of reindex repositories.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositories{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindex Repositories In Progress",
   "type": "table",
   "description": "$Cluster: The number of reindex repositories in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindex Repositories Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent reindexing Lucene repositories.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindexes",
   "type": "table",
   "description": "$Cluster: The number of Lucene reindexes created on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexes{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindexes In Progress",
   "type": "table",
   "description": "$Cluster: The number of reindexes currently in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindexes Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent reindexing Lucene.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexesTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Execution Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent executing Lucene repository queries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Execution Total Hits",
   "type": "table",
   "description": "$Cluster: The total number of documents returned by repository query executions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTotalHits{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Executions",
   "type": "table",
   "description": "$Cluster: The number of Lucene repository queries executed on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutions{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Executions In Progress",
   "type": "table",
   "description": "$Cluster: The number of repository query executions currently in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Update Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent adding or removing documents from the index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Updates",
   "type": "table",
   "description": "$Cluster: The number of Lucene index documents added or removed on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Updates In Progress",
   "type": "table",
   "description": "$Cluster: The number of index updates in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}