{
 "title": "Async Queues",
 "description": "\n",
 "tags": [
  "gemfire",
  "async queue",
  "distribution"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Async Queues: Queue Size",
   "type": "timeseries",
   "description": "$Cluster: Number of events in the async queue.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Async Queues: Queue Count",
   "type": "timeseries",
   "description": "$Cluster: Number of  async queues.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Async Queues",
   "type": "table",
   "description": "$Cluster: Async queue stats",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncQueueAddTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueFlushesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueRemoveTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueSizeExceeded{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueueTimeoutExceeded{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueuedMsgs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncQueues{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}