{
 "title": "Functions",
 "tags": [
  "gemfire",
  "compute",
  "function"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Function Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Function Stats: Average Function Executions Completed Processing Time",
   "type": "timeseries",
   "description": "$Cluster: Average function executions completed processing latency.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}/gemfire_functionExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Function Stats: Function Executions Completed",
   "type": "table",
   "description": "$Cluster: Number of function executions completed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats: Function Execution Calls",
   "type": "table",
   "description": "$Cluster: Number of function execution calls.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionCalls{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats: Function Executions Completed Processing Time",
   "type": "table",
   "description": "$Cluster: Total time took to complete function executions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats: Function Execution Exceptions",
   "type": "table",
   "description": "$Cluster: Number of function execution exceptions.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsExceptions{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats: Function Executions Has Result Completed Processing Time",
   "type": "table",
   "description": "$Cluster: Total time took to process function executions with completed results.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsHasResultCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats: Function Executions Has Result Running",
   "type": "table",
   "description": "$Cluster: Number of function executions with results that are currently running.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsHasResultRunning{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats:  Function Executions Running",
   "type": "table",
   "description": "$Cluster: Number of function executions that are currently running.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsRunning{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats:  Results Received",
   "type": "table",
   "description": "$Cluster: Number of results received.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_resultsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Function Stats:  Results Sent To Result Collector",
   "type": "table",
   "description": "$Cluster: Number of results sent to result collector.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_resultsSentToResultCollector{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Function Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Function Executions",
   "type": "table",
   "description": "$Cluster: Function stats",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionQueueThrottleCount{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionQueueThrottleTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreadJobs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreadStarts{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreads{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}