{
 "title": "Partitioned Regions Columns Charts",
 "tags": [
  "gemfire",
  "partitioned region",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitioned Regions: Entries",
   "type": "barchart",
   "description": "$Cluster: Number of primary entries per member",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Backup Entries",
   "type": "barchart",
   "description": "$Cluster: Number of backup entries per member (custom stats)",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsSize{$ClusterFilterLabel=\"$Cluster\", category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Primary Memory",
   "type": "barchart",
   "description": "$Cluster: Primary value sizes in bytes per member. This does not include keys and entry overheads. ",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Average Object Size",
   "type": "barchart",
   "description": "$Cluster: Average object size in each member's partition region",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}/gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Hits",
   "type": "barchart",
   "description": "$Cluster: Number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"} - gemfire_misses{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Misses",
   "type": "barchart",
   "description": "$Cluster: Number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Updates",
   "type": "barchart",
   "description": "$Cluster: Number of updates performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Puts",
   "type": "barchart",
   "description": "$Cluster: Number of puts performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_puts{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Gets",
   "type": "barchart",
   "description": "$Cluster: Number of gets performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Destroys",
   "type": "barchart",
   "description": "$Cluster: Number of destroys performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_destroys{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Event Threads",
   "type": "barchart",
   "description": "$Cluster: Number of event threads.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventThreads{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Events Queued",
   "type": "barchart",
   "description": "$Cluster: Number of events queued.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Executions",
   "type": "barchart",
   "description": "$Cluster: Number of query executions",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Evictions",
   "type": "barchart",
   "description": "$Cluster: Number of evictions by criteria.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_evictByCriteria_evictions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: TX Rollbacks",
   "type": "barchart",
   "description": "$Cluster: Number of transaction rollbacks.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txRollbacks{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: TX Failures",
   "type": "barchart",
   "description": "$Cluster: Number of transaction failures.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txFailures{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}