{
 "title": "Clients",
 "tags": [
  "gemfire",
  "cluster",
  "client"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Client Notifier",
   "type": "table",
   "description": "$Cluster: Statistics regarding cache server operations sent to all clients.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_durableReconnectionCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_events{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsEnqueuedWhileClientAwayCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueDroppedCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}