{
 "title": "Member Region Activities",
 "tags": [
  "gemfire",
  "member region"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "$Cluster: put() Requests Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_putRequests{job=\"$Cluster\",category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: get() Requests Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_getRequests{job=\"$Cluster\",category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: putAll() Requests Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gemfire_putAllRequests{job=\"$Cluster\",category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: getAll() Requests Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "gemfire_getAllRequests{job=\"$Cluster\",category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Regions Heatmap Top 10",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by(exported_instance) (gemfire_writtenBytes{job=\"$Cluster\", category=\"DiskRegionStatistics\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Regions Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(gemfire_writtenBytes{job=\"$Cluster\", category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}