{
 "title": "Member",
 "tags": [
  "gemfire",
  "member",
  "single"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "Member",
    "query": {
     "query": "label_values(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Member" },
  {
   "title": "GemFire Cluster Member",
   "type": "text",
   "description": "Name of member clustered in $Cluster",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "# ${Member}" }
  },
  {
   "title": "Memory: Free, Used",
   "type": "piechart",
   "description": "$Member: free vs. used memory",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_freeMemory{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Member Resources",
   "type": "table",
   "description": "$Member: Member resource overview",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\",instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "$Member: Member system CPU usage with the threshold set at 90%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "$Member: Member threads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_threads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "gemfire_partitionedRegionThreads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Partitioned Region"
    },
    {
     "expr": "gemfire_longRunningThreads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Long Running"
    },
    {
     "expr": "gemfire_peakThreads{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "gemfire_numThreadsStuck{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "Stuck"
    }
   ]
  },
  {
   "title": "Used Heap and Thresholds",
   "type": "timeseries",
   "description": "$Member: Used heap, eviction threshold, critical threshold, and max heap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\", instance=\"$Member\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "gemfire_evictionThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Threshold"
    },
    {
     "expr": "gemfire_criticalThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical Threshold"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\",instance=\"$Member\"}",
     "legendFormat": "Max Heap Threshold"
    }
   ]
  },
  {
   "title": "GC Count: Pauses, Cycles",
   "type": "timeseries",
   "description": "$Member: Member ZGC pause and cycle count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\", instance=\"$Member\"}",
     "legendFormat": "GC Minor Count"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\", instance=\"$Member\"}",
     "legendFormat": "GC Major Count"
    }
   ]
  },
  {
   "title": "Swapped Pages",
   "type": "timeseries",
   "description": "$Member: Total number of swap pages that have been read in from disk by the operating system’s memory manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_pagesSwappedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Swapped In"
    },
    {
     "expr": "gemfire_pagesSwappedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Swapped Out"
    }
   ]
  },
  {
   "title": "Page Count",
   "type": "timeseries",
   "description": "$Member: Total number of pages that have been brought into memory from disk by the operating system’s memory manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_pagesPagedIn{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Page In"
    },
    {
     "expr": "gemfire_pagesPagedOut{$ClusterFilterLabel=\"$Cluster\",category=\"LinuxSystemStats\", instance=\"$Member\"}",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Heap Events",
   "type": "timeseries",
   "description": "$Member: Heap events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_heapSafeEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Safe"
    },
    {
     "expr": "gemfire_evictionStartEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction"
    },
    {
     "expr": "gemfire_evictionStopEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Stop"
    },
    {
     "expr": "gemfire_heapCriticalEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Used NonHeap",
   "type": "timeseries",
   "description": "$Member: Used non-heap memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Off-Heap Thresholds",
   "type": "timeseries",
   "description": "$Member: Off-heap thresholds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_offHeapEvictionThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Threshold"
    },
    {
     "expr": "gemfire_offHeapCriticalThreshold{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical Threshold"
    }
   ]
  },
  {
   "title": "Off-Heap Events",
   "type": "timeseries",
   "description": "$Member: Off-heap events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_offHeapSafeEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Safe"
    },
    {
     "expr": "gemfire_offHeapEvictionStartEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction"
    },
    {
     "expr": "gemfire_offHeapEvictionStopEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Eviction Stop"
    },
    {
     "expr": "gemfire_offHeapCriticalEvents{$ClusterFilterLabel=\"$Cluster\",category=\"ResourceManagerStats\", instance=\"$Member\"}",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Partitioned Regions",
   "type": "table",
   "description": "All partitioned regions in $Member sorted by descending order of entries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Regions",
   "type": "table",
   "description": "All replicated regions in $Member sorted by descending order of entries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Normal (Local) Regions",
   "type": "table",
   "description": "All normal (local) regions in $Member sorted by descending order of entries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Structures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Partition Distribution (Primary)",
   "type": "bargauge",
   "description": "$Cluster: Number of primary buckets per partitioned region. Sorted in descending order.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(gemfire_primaryBucketCount{job=\"$Cluster\",instance=\"$Member\",category=\"PartitionedRegionStats\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Partition Distribution (Backup)",
   "type": "bargauge",
   "description": "$Cluster: Number of redundant buckets per partitioned region. Sorted in descending order. (custom stats)",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(gemfire_redundantBucketsCount{job=\"$Cluster\",instance=\"$Member\",category=\"McPartitionedRegionStats\"})",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}