{
 "title": "Partitioned Regions Query Charts",
 "tags": [
  "gemfire",
  "query",
  "partitioned region",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query Executions",
   "type": "barchart",
   "description": "$Cluster: Number of queries executed on the region.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region Query Count (aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Number of queries executed performed on all regions",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(gemfire_queryRequests{$ClusterFilterLabel=\"$Cluster\",category=\"CacheServerStats\"})",
     "legendFormat": "Query Requests"
    },
    {
     "expr": "sum(gemfire_queryResponses{$ClusterFilterLabel=\"$Cluster\",category=\"CacheServerStats\"})",
     "legendFormat": "Query Responses"
    },
    {
     "expr": "sum(gemfire_partitionedRegionQueryRetries{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"})",
     "legendFormat": "Query Retries"
    },
    {
     "expr": "sum(gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster\",category=\"CacheClientNotifierStatistics\"})",
     "legendFormat": "Compiled Query Count"
    },
    {
     "expr": "sum(gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster\",category=\"CacheClientNotifierStatistics\"})",
     "legendFormat": "Compiled Query Used Count"
    }
   ]
  },
  {
   "title": "CQ Query (aggregate)",
   "type": "timeseries",
   "description": "$Cluster: CQ query execution stats",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Executions Completed"
    },
    {
     "expr": "sum(gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Execution In Progress"
    },
    {
     "expr": "sum(gemfire_numUniqueCqQuery{$ClusterFilterLabel=\"$Cluster\",category=\"CqServiceStats\"})",
     "legendFormat": "Unique Query Count"
    }
   ]
  }
 ]
}