{
 "title": "Replicated Regions Rows",
 "tags": [
  "gemfire",
  "data structure",
  "replicated region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Replicated/Local Regions: Entries",
   "type": "table",
   "description": "$Cluster: Number of region entries per member",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entries{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Cache Misses",
   "type": "table",
   "description": "$Cluster: Total number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Cache Hits",
   "type": "table",
   "description": "$Cluster: Total number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}-gemfire_misses{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}