{
 "title": "Replicated Regions Rows Charts",
 "tags": [
  "gemfire",
  "data structure",
  "replicated region"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Replicated/Local Regions: Entries",
   "type": "barchart",
   "description": "$Cluster: Number of region entries per member",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_entries{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Event Queue Size",
   "type": "barchart",
   "description": "$Cluster: Number of region events in the queue",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entries",
   "type": "barchart",
   "description": "$Cluster: Number of entries owned on this member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entry Memory",
   "type": "barchart",
   "description": "$Cluster: Memory cost of owned entries on this member",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Hits",
   "type": "barchart",
   "description": "$Cluster: Number of hits (reads) of the locally owned entries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Events",
   "type": "barchart",
   "description": "$Cluster: Number of events received on this member",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Other Operations",
   "type": "barchart",
   "description": "$Cluster: Total number of other operations performed on this member",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Total Operations",
   "type": "barchart",
   "description": "$Cluster: Total number of operations on this member",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_total{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Put Count",
   "type": "barchart",
   "description": "$Cluster: Number of put operations on this member",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Get Count",
   "type": "barchart",
   "description": "$Cluster: Number of get operations on this member",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Remove Count",
   "type": "barchart",
   "description": "$Cluster: Number of remove operations on this member",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Put Latency",
   "type": "barchart",
   "description": "$Cluster: Total latency of put operations",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_maxPutLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Get Latency",
   "type": "barchart",
   "description": "$Cluster: Total latency of get operations",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_maxGetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Remove Latency",
   "type": "barchart",
   "description": "$Cluster: Total latency of remove operations",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_maxRemoveLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}