{
 "title": "System Resources",
 "tags": [
  "gemfire",
  "resources",
  "memory",
  "os",
  "jvm",
  "performance",
  "latency",
  "throughput"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "$Cluster: Number of running data nodes in the cluster excluding locators",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_nodes{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "$Cluster: Member resource statuses",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Aggregates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Heap Memory: Free, Used (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Regions: Entries",
   "type": "stat",
   "description": "$Cluster: Number of entries per region in descending order. Displays up to top 15 regions.",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Max ZGC Count: Cycles, Pauses (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: ZGC cycle and pause count of the member with the highest value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"})",
     "legendFormat": "ZGC Cycles"
    },
    {
     "expr": "max(gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"})",
     "legendFormat": "ZGC Pauses"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Used Heap (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member used heap memories",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    }
   ]
  },
  {
   "title": "OffHeap Memory (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member off-heap memories",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_offHeapUsedMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gemfire_offHeapFreeMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gemfire_offHeapMaxMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Physical Memory (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Physical memory of the member with the highest value",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(com_gemfire_Metrics_freePhysical{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Physical Memory"
    },
    {
     "expr": "max(com_gemfire_Metrics_totalPhysicalMemorySize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Total Physical Memory"
    }
   ]
  },
  {
   "title": "Thread Count (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member threads",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(com_gemfire_Metrics_threadCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Active"
    },
    {
     "expr": "sum(com_gemfire_Metrics_peakThreadCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Peak"
    },
    {
     "expr": "sum(com_gemfire_Metrics_daemonThreadCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Daemon"
    }
   ]
  },
  {
   "title": "Committed Memory (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member committed heap memories",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_gemfire_Metrics_committedHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Committed Heap"
    },
    {
     "expr": "sum(com_gemfire_Metrics_committedNative{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Committed Native"
    },
    {
     "expr": "sum(com_gemfire_Metrics_committedVirtualMemorySize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Committed Virtual"
    }
   ]
  },
  {
   "title": "Memory Maps (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member owned entry memory costs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_gemfire_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Primary Maps"
    },
    {
     "expr": "sum(com_gemfire_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Backup Maps"
    }
   ]
  },
  {
   "title": "Total Swap Space (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Sum of all member free swap space sizes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_gemfire_Metrics_freeSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "sum(com_gemfire_Metrics_totalSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Max File Descriptors (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Open filed descriptor count of the member with the highest value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "max(com_gemfire_Metrics_openFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Open FD"
    },
    {
     "expr": "max(com_gemfire_Metrics_maxFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Max FD"
    }
   ]
  },
  { "title": "Per Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Free Memory (Per Member)",
   "type": "piechart",
   "description": "$Cluster: Free memory per member",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Distribution (Per Member)",
   "type": "piechart",
   "description": "$Cluster: Partition count per member",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Count: Minor, Major (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: GC minor and major count of each member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "{{instance}} Minor"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "{{instance}} Major"
    }
   ]
  },
  {
   "title": "System CPU Load (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: System CPU load of each member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Heap memory of each member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "com_gemfire_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "com_gemfire_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Used Heap (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Used heap memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Native (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Used native memory of each member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Physical Memory (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Physical memory of each member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_freePhysical{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "com_gemfire_Metrics_totalPhysicalMemorySize{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": " {{instance}} Total"
    }
   ]
  },
  {
   "title": "Thread Count (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Thread count of each member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_threadCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Active"
    },
    {
     "expr": "com_gemfire_Metrics_peakThreadCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Peak"
    },
    {
     "expr": "com_gemfire_Metrics_daemonThreadCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Daemon"
    }
   ]
  },
  {
   "title": "Swap Space (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Swap space size of each member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_freeSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "com_gemfire_Metrics_totalSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "File Descriptors (Per Member)",
   "type": "timeseries",
   "description": "$Cluster: Number of open and max file descriptors per member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_openFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Open"
    },
    {
     "expr": "com_gemfire_Metrics_maxFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  }
 ]
}