{
 "title": "Dual WAN",
 "tags": [
  "dual gemfire",
  "wan",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "Wan",
    "label": "WAN",
    "query": {
     "query": "label_values(com_gemfire_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster\"},tag1)"
    }
   },
   {
    "name": "WanPublisherId",
    "label": "Publisher",
    "query": {
     "query": "label_values(com_gemfire_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster\", tag1=~\".*replication=$Wan.*\"},tag0)"
    }
   },
   {
    "name": "Wan2",
    "label": "WAN 2",
    "query": {
     "query": "label_values(com_gemfire_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster2\"},tag1)"
    }
   },
   {
    "name": "WanPublisherId2",
    "label": "Publisher 2",
    "query": {
     "query": "label_values(com_gemfire_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster2\", tag1=~\".*replication=$Wan2.*\"},tag0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WAN Replication",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**WAN Standard:** *Standard WAN metrics included in GemFire.* **WAN Discovery Plugin:** *WAN plugin by Sorint.lab (reduces WAN endpoint discovery latency by 1000x)*"
   }
  },
  { "title": "WAN Standard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Members ($Cluster: $Wan $WanPublisherId)",
   "type": "table",
   "description": "$Cluster: WAN replication outbound queue status",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_outboundQueueSize{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_queueFillPercent{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalPublishLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalPublishedEventCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayLastStart{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayLastEnd{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayTotalCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayTotalMillis{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members ($Cluster2: $Wan2 $WanPublisherId2)",
   "type": "table",
   "description": "$Cluster2: WAN replication outbound queue status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_outboundQueueSize{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag1=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_queueFillPercent{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag1=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalPublishLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag1=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalPublishedEventCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag1=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayLastStart{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayLastEnd{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayTotalCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_ackDelayTotalMillis{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Update Events ($Cluster: $Wan $WanPublisherId)",
   "type": "table",
   "description": "$Cluster: Number of entry update events",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Update Events ($Cluster2: $Wan2 $WanPublisherId2)",
   "type": "table",
   "description": "$Cluster2: Number of entry update events",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag2=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Remove Events ($Cluster: $Wan $WanPublisherId)",
   "type": "table",
   "description": "$Cluster: Number of entry remove events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Remove Events ($Cluster2: $Wan2 $WanPublisherId2)",
   "type": "table",
   "description": "$Cluster2: Number of entry remove events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag2=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Sync Events ($Cluster: $Wan $WanPublisherId)",
   "type": "table",
   "description": "$Cluster: Number of entry sync events",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_syncCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Sync Events ($Cluster2: $Wan2 $WanPublisherId2)",
   "type": "table",
   "description": "$Cluster2: Number of entry sync events",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_syncCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag2=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dropped Entry Events ($Cluster: $Wan $WanPublisherId)",
   "type": "table",
   "description": "$Cluster: Number of dropped entry events",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_droppedCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dropped Entry Events ($Cluster2: $Wan2 $WanPublisherId2)",
   "type": "table",
   "description": "$Cluster2: Number of dropped entry events",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_droppedCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId2\\\"\", tag2=\"\\\"replication=$Wan2\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN Discovery Plugin ($Cluster: $Wan $WanPublisherId) ($Cluster2: $Wan 2$WanPublisherId2)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "WAN Discovery: Live Endpoints",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "org_gemfire_addon_IpDiscoveryStatus_LiveTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",type=\"DiscoveryService\"}",
     "legendFormat": "Live"
    }
   ]
  },
  {
   "title": "WAN Discovery: Dead Endpoints",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "org_gemfire_addon_IpDiscoveryStatus_DeadTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",type=\"DiscoveryService\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN Discovery: All Endpoints",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "org_gemfire_addon_IpDiscoveryStatus_TargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",type=\"DiscoveryService\"}",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "WAN Discovery: Live Endpoints ($Cluster2)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "org_gemfire_addon_IpDiscoveryStatus_LiveTargetEndpointCount{$ClusterFilterLabel=\"$Cluster2\",type=\"DiscoveryService\"}",
     "legendFormat": "Live"
    }
   ]
  },
  {
   "title": "WAN Discovery: Dead Endpoints ($Cluster2)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "org_gemfire_addon_IpDiscoveryStatus_DeadTargetEndpointCount{$ClusterFilterLabel=\"$Cluster2\",type=\"DiscoveryService\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN Discovery: All Endpoints ($Cluster2)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "org_gemfire_addon_IpDiscoveryStatus_TargetEndpointCount{$ClusterFilterLabel=\"$Cluster2\",type=\"DiscoveryService\"}",
     "legendFormat": "All"
    }
   ]
  }
 ]
}