{
 "title": "Dual Partitioned Regions Query Charts",
 "tags": [
  "dual gemfire",
  "query",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Map Query Count (aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of queries executed and indexed local queries performed on all maps",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(com_gemfire_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map\"})",
     "legendFormat": "Indexed Query Count"
    }
   ]
  },
  {
   "title": "Map Query Count (aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of queries executed and indexed local queries performed on all maps",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(com_gemfire_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map\"})",
     "legendFormat": "Indexed Query Count"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Latency ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Average hit latency on the index across all members in the cluster",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(com_gemfire_Metrics_averageHitLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"})",
     "legendFormat": "Average Hit Latency"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Latency ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Average hit latency on the index across all members in the cluster",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(com_gemfire_Metrics_averageHitLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"})",
     "legendFormat": "Average Hit Latency"
    }
   ]
  },
  {
   "title": "Indexes: Map Average Total Latencies ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Average total latencies for index write operations across all members in the cluster",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(com_gemfire_Metrics_totalInsertLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"})",
     "legendFormat": "Average Total Insert Latency"
    },
    {
     "expr": "avg(com_gemfire_Metrics_totalUpdateLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"})",
     "legendFormat": "Average Total Update Latency"
    },
    {
     "expr": "avg(com_gemfire_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"})",
     "legendFormat": "Average Total Remove Latency"
    }
   ]
  },
  {
   "title": "$Cluster2: Indexes: Map Average Total Latencies ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Average total latencies for index write operations across all members in the cluster",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(com_gemfire_Metrics_totalInsertLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"})",
     "legendFormat": "Average Total Insert Latency"
    },
    {
     "expr": "avg(com_gemfire_Metrics_totalUpdateLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"})",
     "legendFormat": "Average Total Update Latency"
    },
    {
     "expr": "avg(com_gemfire_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"})",
     "legendFormat": "Average Total Remove Latency"
    }
   ]
  },
  {
   "title": "Indexes: Insert Count ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Number of insert operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_insertCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Insert Count ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Number of insert operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_insertCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Insert Latency ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Total latency of update operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalInsertLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Insert Latency ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Total latency of update operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalInsertLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Update Count ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Number of update operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Update Count ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Number of update operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Update Latency ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Total latency of update operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalUpdateLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Update Latency ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Total latency of update operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalUpdateLatency{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Remove Count ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Number of remove operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Remove Count ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Number of remove operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Remove Latency ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Total latency of remove operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Remove Latency ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Total latency of remove operations performed on the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Count ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Total number of index hits (the value of this metric may be greater than the map.index.queryCount since a single query may hit the same index more than once)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hitCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Count ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Total number of index hits (the value of this metric may be greater than the map.index.queryCount since a single query may hit the same index more than once)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hitCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Index Hit Latency ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Average hit latency for the index on each member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_averageHitLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Index Hit Latency ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Average hit latency for the index on each member",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_averageHitLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Aveage Hit Selectivity ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Average selectivity of the hits served by the index on this member (the returned value is in the range from 0.0 to 1.0 - values close to 1.0 indicate a high selectivity meaning the index is efficient; values close to 0.0 indicate a low selectivity meaning the index efficiency is approaching an efficiency of a simple full scan)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_averageHitSelectivity{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Aveage Hit Selectivity ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Average selectivity of the hits served by the index on this member (the returned value is in the range from 0.0 to 1.0 - values close to 1.0 indicate a high selectivity meaning the index is efficient; values close to 0.0 indicate a low selectivity meaning the index efficiency is approaching an efficiency of a simple full scan)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_averageHitSelectivity{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Query Count ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Total number of queries served by the index",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Query Count ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Total number of queries served by the index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_memoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_memoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}