{
 "title": "Dual Distributed Locks",
 "tags": [
  "dual gemfire",
  "messaging",
  "lock"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Topics: Published Messages ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of published messages of this topic on this member",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalPublishes{$ClusterFilterLabel=\"$Cluster\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics: Published Messages ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of published messages of this topic on this member",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalPublishes{$ClusterFilterLabel=\"$Cluster2\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics: Received Messages ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of received messages of this topic on this member",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalReceivedMessages{$ClusterFilterLabel=\"$Cluster\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics: Received Messages ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of received messages of this topic on this member",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalReceivedMessages{$ClusterFilterLabel=\"$Cluster2\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}