{
 "title": "All Search Lucene",
 "tags": [
  "all gemfire",
  "compute",
  "lucene"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lucene Indexes: Average Query Execution Time",
   "type": "timeseries",
   "description": "Average Lucene query execution latency.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}/gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Executions",
   "type": "table",
   "description": "The number of Lucene queries executed on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Execution Time",
   "type": "table",
   "description": "The amount of time spent executing Lucene queries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Execution Total Hits",
   "type": "table",
   "description": "The total number of documents returned by query executions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTotalHits{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Query Executions In Progress",
   "type": "table",
   "description": "The number of query executions currently in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Commit Time",
   "type": "table",
   "description": "The amount of time spent in Lucene index commits.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_commitTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Commits",
   "type": "table",
   "description": "The number of Lucene index commits on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commits{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Commits In Progress",
   "type": "table",
   "description": "The number of Lucene index commits in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commitsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Documents",
   "type": "table",
   "description": "The number of documents in the index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_documents{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Failed Entries",
   "type": "table",
   "description": "The number of failed entries for the index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_failedEntries{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindex Repositories",
   "type": "table",
   "description": "The number of reindex repositories.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositories{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindex Repositories In Progress",
   "type": "table",
   "description": "The number of reindex repositories in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindex Repositories Time",
   "type": "table",
   "description": "The amount of time spent reindexing Lucene repositories.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindexes",
   "type": "table",
   "description": "The number of Lucene reindexes created on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexes{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindexes In Progress",
   "type": "table",
   "description": "The number of reindexes currently in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Reindexes Time",
   "type": "table",
   "description": "The amount of time spent reindexing Lucene.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexesTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Execution Time",
   "type": "table",
   "description": "The amount of time spent executing Lucene repository queries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Execution Total Hits",
   "type": "table",
   "description": "The total number of documents returned by repository query executions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTotalHits{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Executions",
   "type": "table",
   "description": "The number of Lucene repository queries executed on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutions{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Repository Query Executions In Progress",
   "type": "table",
   "description": "The number of repository query executions currently in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Update Time",
   "type": "table",
   "description": "The amount of time spent adding or removing documents from the index.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Updates",
   "type": "table",
   "description": "The number of Lucene index documents added or removed on the member.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lucene Indexes: Updates In Progress",
   "type": "table",
   "description": "The number of index updates in progress.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}