{
 "title": "All Replicated Regions Columns Charts",
 "tags": [
  "all gemfire",
  "storage",
  "replicated region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicated/Local Regions: Entries",
   "type": "barchart",
   "description": "$Cluster: Number of replicated region entries owned by the member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_entries{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Cache Hits",
   "type": "barchart",
   "description": "$Cluster: Number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}-gemfire_misses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Cache Misses",
   "type": "barchart",
   "description": "$Cluster: Number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Cache Updates",
   "type": "barchart",
   "description": "$Cluster: Number of updates performed on the region.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Puts",
   "type": "barchart",
   "description": "$Cluster: Number of puts performed on the region.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_puts{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Gets",
   "type": "barchart",
   "description": "$Cluster: Number of gets performed on the region.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Events Queued",
   "type": "barchart",
   "description": "$Cluster: Number of events queued.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Event Threads",
   "type": "barchart",
   "description": "$Cluster: Number of event threads.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventThreads{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Evictions",
   "type": "barchart",
   "description": "$Cluster: Number of evictions by criteria.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_evictByCriteria_evictions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: Query Executions",
   "type": "barchart",
   "description": "$Cluster: Number of query executions",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: TX Failures",
   "type": "barchart",
   "description": "$Cluster: Number of transaction failures.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated/Local Regions: TX Rollbacks",
   "type": "barchart",
   "description": "$Cluster: Number of transaction rollbacks.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txRollbacks{$ClusterFilterLabel=~\"$ClusterList\"\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}