{
 "title": "All Partitioned Regions Query Tables",
 "tags": [
  "query",
  "all gemfire",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitioned Regions: Query Executions",
   "type": "table",
   "description": "Number of query executions per region.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Execution Time",
   "type": "table",
   "description": "Time took to complete query executions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Results Hash Collision Probe Time",
   "type": "table",
   "description": "Time took to probe query results hash collisions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryResultsHashCollisionProbeTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Results Hash Collisions",
   "type": "table",
   "description": "Number of query results hash collisions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryResultsHashCollisions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Retries",
   "type": "table",
   "description": "Number of query retries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueryRetries{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}