{
 "title": "All Partitioned Regions Rows",
 "tags": [
  "all gemfire",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitioned Regions: Entries",
   "type": "table",
   "description": "$Cluster: Number of region entries per member",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Backup Entries",
   "type": "table",
   "description": "$Cluster: Number of backup entries held by each member (Mastercard custom stats).",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Primary Memory",
   "type": "table",
   "description": "$Cluster: Primary value sizes in bytes per member. This does not include keys and entry overheads. ",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Average Object Size",
   "type": "table",
   "description": "$Cluster: Average object size in each member's partition region",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}/gemfire_dataStoreEntryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Hits",
   "type": "table",
   "description": "$Cluster: Total number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"} - gemfire_misses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Misses",
   "type": "table",
   "description": "$Cluster: Total number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Updates",
   "type": "table",
   "description": "$Cluster: Number of updates performed on the region.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Puts",
   "type": "table",
   "description": "$Cluster: Number of puts performed on the region.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_puts{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Gets",
   "type": "table",
   "description": "$Cluster: Number of gets performed on the region.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Destroys",
   "type": "table",
   "description": "$Cluster: Number of destroys performed on the region.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_destroys{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Event Threads",
   "type": "table",
   "description": "$Cluster: Number of event threads.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_eventThreads{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Events Queued",
   "type": "table",
   "description": "$Cluster: Number of events queued.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Executions",
   "type": "table",
   "description": "$Cluster: Number of query executions",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Evictions",
   "type": "table",
   "description": "$Cluster: Number of evictions by criteria.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_evictByCriteria_evictions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: TX Rollbacks",
   "type": "table",
   "description": "$Cluster: Number of transaction rollbacks.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_txRollbacks{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: TX Failures",
   "type": "table",
   "description": "$Cluster: Number of transaction failures.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_txFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}