{
 "title": "All Clients",
 "tags": [
  "cluster",
  "client",
  "all gemfire"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "description": "$Cluster: Number of client virtual machines (clients) connected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "Connection Threads",
   "type": "timeseries",
   "description": "$Cluster: The current number of threads dealing with a client connection and the total number of threads created (starts) to deal with a client connection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Threads"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Thread Starts"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Client Notifier",
   "type": "table",
   "description": "$Cluster: Statistics regarding cache server operations sent to all clients.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryUsedCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqProcessingTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_durableReconnectionCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventProcessingTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_events{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsEnqueuedWhileClientAwayCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueDroppedCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients",
   "type": "table",
   "description": "Client connections and activities overview",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}