{
 "title": "All Locators",
 "tags": [
  "all gemfire",
  "locator",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "LocatorCluster",
    "label": "LocatorCluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "LocatorCluster2",
    "label": "LocatorCluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "LocatorClusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locators: Up Time",
   "type": "stat",
   "description": "Cluster up time determined by the oldest locator per cluster",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gemfire_process_uptime_seconds{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"locator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Count",
   "type": "stat",
   "description": "Number of running locators per cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"locator\"} + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Conn Requests",
   "type": "stat",
   "description": "Total number of client connection requests per cluster",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Client Conn Request Time",
   "type": "stat",
   "description": "Average client connection request time per cluster",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "description": "Total number of locator requests in progress per cluster",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_requestsInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Conn Response Failures",
   "type": "stat",
   "description": "Total number of client connection response failures per cluster",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators Resources",
   "type": "table",
   "description": "Locator resource stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=~\"$ClusterList\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}/gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMStats\",exported_instance=\"vmStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ParNew\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ConcurrentMarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"PS Scavenge\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"PS MarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"G1 Young Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"G1 Old Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Client Connection",
   "type": "table",
   "description": "Client connection request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Client Replacement",
   "type": "table",
   "description": "$Cluster: Client replacement request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Find Coordinator",
   "type": "table",
   "description": "$Cluster: Find coordinator request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_findCoordinatorRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Get All Servers",
   "type": "table",
   "description": "$Cluster: Get all servers request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getAllServersRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Get View",
   "type": "table",
   "description": "$Cluster: Get view request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getViewRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Locator List",
   "type": "table",
   "description": "$Cluster: Locator list request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorListRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Locator Status",
   "type": "table",
   "description": "$Cluster: Locator status request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorStatusRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Queue Connection",
   "type": "table",
   "description": "$Cluster: Queue connection request and response stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queueConnectionRequestFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Processing, Servers, Locators",
   "type": "table",
   "description": "$Cluster: Request and response processing time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_requestProcessingFailureTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestProcessingTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestsInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingFailureTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_serverLoadUpdates{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_servers{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=~\"$ClusterList\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}