{
 "title": "All Indexes",
 "tags": [
  "all gemfire",
  "compute",
  "index"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Index Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index Stats: Bucket Indexes",
   "type": "table",
   "description": "Number of bucket indexes.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numBucketIndexes{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Keys",
   "type": "table",
   "description": "Number of keys.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numKeys{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Map Index Keys",
   "type": "table",
   "description": "Number of map index keys.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numMapIndexKeys{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Updates",
   "type": "table",
   "description": "Number of updates.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numUpdates{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Uses",
   "type": "table",
   "description": "Number of uses.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numUses{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Values",
   "type": "table",
   "description": "Number of values.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numValues{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Read Lock Count",
   "type": "table",
   "description": "Number of read locks.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_readLockCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Update Time",
   "type": "table",
   "description": "Update time.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Updates in Progress",
   "type": "table",
   "description": "Number of updates in progress.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Use Time",
   "type": "table",
   "description": "Use time.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_useTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Stats: Uses in Progress",
   "type": "table",
   "description": "Number uses in progress.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_usesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Index Status per Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Index Initialization Completed",
   "type": "table",
   "description": "$Cluster: Number of index initialization completed.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Initialization in Progress",
   "type": "table",
   "description": "$Cluster: Number of index initialization in progress.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Initialization Time",
   "type": "table",
   "description": "$Cluster: Index initialization latency",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationTime{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Update Completed",
   "type": "table",
   "description": "$Cluster: Number of index updates completed",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Update in Progress",
   "type": "table",
   "description": "$Cluster: Number of index updates in progress",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Update Time",
   "type": "table",
   "description": "$Cluster: Index update latency",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateTime{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}