{
 "title": "All Distributed Locks",
 "tags": [
  "all gemfire",
  "messaging",
  "lock"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Distributed Locks: Average Lock Release Time",
   "type": "timeseries",
   "description": "Average time took to release a lock per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}/gemfire_lockReleasesCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Locks: Lock Releases In Progress",
   "type": "timeseries",
   "description": "Number of lock releases in progress per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockReleasesInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Locks: Average Lock Wait Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to wait for a lock per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}/gemfire_lockWaitsCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Locks: Lock Waits In Progress",
   "type": "timeseries",
   "description": "Number of lock waits in progress per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitsInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Locks: Average Lock Wait Failed Time",
   "type": "timeseries",
   "description": "Average time took for a lock wait to fail per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}/gemfire_lockWaitsFailed{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Locks: Lock Waits Failed",
   "type": "timeseries",
   "description": "Number of lock waits failed per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitsFailed{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distributed Locks Stats",
   "type": "table",
   "description": "Distributed Locks stats",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}/gemfire_lockReleasesCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleasesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}