{
 "title": "All Partitions",
 "tags": [
  "all gemfire",
  "partition"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitioned Region Queue Size",
   "type": "timeseries",
   "description": "Number of events in the partitioned region queue.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueueSize{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Primary Buckets",
   "type": "barchart",
   "description": "Number of primary entries per member",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Redundant Buckets",
   "type": "barchart",
   "description": "Number of redundant buckets per partitioned region (Mastercard custom stats).",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Region Queues, Threads",
   "type": "table",
   "description": "Partitioned region queue and thread stats",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueueSize{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionQueueThrottleCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionQueueThrottleTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadStarts{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreads{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Primary Buckets",
   "type": "table",
   "description": "Number of primary buckets per partitioned region.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Redundant Buckets",
   "type": "table",
   "description": "Number of backup buckets per partitioned region (Mastercard custom stats)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}