{
 "title": "00Dual Main",
 "tags": [
  "dual gemfire",
  "dual main"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dual Main Dashboard",
   "type": "text",
   "description": "The main dashboard of PadoGrid GemFire Dashboards (PHD) that resembles the main dashboard of GemFire Management Center (HMC). PHD includes additional metrics that are not available in HMC and vice versa. PHD exposes a finer degree of individual metric details along with federated cluster views making it more suitable for monitoring production systems.",
   "gridPos": { "h": 40, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "## Main\n\n- [Main Dashboard](/d/ed5d1905-d13d-446a-83d5-3d33d3aadddc/00main?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Dual Main Dashboard](/d/2f6503d9-5b23-4af6-9a87-08f799229df5/00dual-main?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [All Main Dashboard](/d/5a076038-1d97-4c44-abe7-26020351d90b/00main-all?${__url_time_range})\n\n## Cluster\n\n- [Dual Clients](/d/d2a70fcc-3d13-4e5d-b3a8-7bb1cd5b9de7/dual-clients?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Members](/d/bed72936-7b5d-484b-8ace-a5d2f9acbb1a/dual-members?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Locators](/d/5838f815-c8ca-48a9-afb1-d1448d839919/dual-jet?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual WAN Replication](/d/f10ab12f-ec25-4c47-a8b5-47d1707dba9f/dual-wan?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Storage\n\n- [Dual Partitioned Regions](/d/68872fcb-1dff-43f9-aeb3-28675bf6bc82/dual-partitioned_regions?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Column Charts](/d/8ce56ff5-2797-4d20-908b-26a64365659c/dual-partitioned_regions-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Column Tables](/d/5b5ae01d-6c1a-4f6e-8436-50c594f9c1be/dual-partitioned_regions-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Row Charts](/d/6f6cbfc8-db19-4503-a197-f7a1173cddf2/dual-partitioned_regions-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Row Tables](/d/0089926c-8f68-4ab9-ac24-c5402f71eb20/dual-partitioned_regionsmaps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Query Charts](/d/eef75991-b012-473a-97f1-15d40a92c1a2/dual-partitioned_regions-query?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Query Tables](/d/217e8e5c-460f-42f6-ad82-b8571786fd6f/dual-partitioned_regions-query-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Replicated Regions](/d/c2add9fe-f8ef-471f-85bd-e279ccbc35ea/dual-replicated-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Column Charts](/d/78c313f4-8598-4c86-ad93-677a5243628d/dual-replicated-regions-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Column Tables](/d/15169590-00e9-445e-acd5-f6dbb1e161f6/dual-replicated-regions-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Row Charts](/d/df249eda-6210-4fba-864d-cb61fa2c8f4b/dual-replicated-regions-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Row Tables](/d/c2add9fe-f8ef-471f-85bd-e279ccbc35ea/dual-replicated-regions-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Disk Stores](/d/a38c9a6e-ddfb-4fd2-804f-e066f4276157/dual-disk-stores-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Column Charts](/d/4a68ce9e-066d-46be-87a4-20a4fab4409c/dual-disk-stores-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Column Tables](/d/5b5ae01d-6c1a-4f6e-8436-50c594f9c1be/dual-maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Row Charts](/d/4a68ce9e-066d-46be-87a4-20a4fab4409c/dual-disk-stores-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Row Tables](/d/a38c9a6e-ddfb-4fd2-804f-e066f4276157/dual-disk-stores-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Dual Partition\n\n- [Dual Partitions](/d/3d3767c2-a607-4b71-8ebf-a58336d11354/dual-partitions?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Compute\n\n- [Dual Functions](/d/2a25b9a9-300f-4f9e-896e-0c19326f7ab6/dual-functions?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Lucene](/d/34b13ca6-fe20-47b4-a7a6-6ca8efcdc22f/dual-lucene?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Indexes](/d/c4994f15-e364-46e9-bb7f-b386636b36ab/dual-indexes?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual PDX](/d/d9e2f58f-b56d-4fbc-9001-b76b9ac5e149/dual-pdx?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Messaging\n\n- [Dual Async Queues](/d/335bb399-92a9-475e-b9b7-a2104b581f1d/dual-async-queues?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual CQ](/d/71b39248-eccb-4974-b378-c0644cff627f/dual-cq?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Distribution](/d/e51d6022-df1c-4d1b-89ef-fbe128db1d16/dual-distribution?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Distributed Locks](/d/2b0b9f0f-5e01-4489-b153-7a5c934f4d51/dual-distributed-locks?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Linux\n\n- [Dual Linux Systems](/d/f890f5e3-abb1-43a6-bd05-ad5ca357d4cd/dual-linux-systems?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})"
   }
  },
  {
   "title": "Cluster Up Time ($Cluster)",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Heap Memory: Free, Used (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Regions: Entries",
   "type": "stat",
   "description": "$Cluster: Number of entries per region in descending order. Displays up to top 15 regions.",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Cluster Up Time ($Cluster2)",
   "type": "stat",
   "description": "$Cluster2: Cluster up time determined by the oldest member",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Heap Memory: Free, Used (Aggregate) ($Cluster2)",
   "type": "piechart",
   "description": "$Cluster2: Free memory vs. used memory",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    }
   ]
  },
  {
   "title": "Regions: Entries ($Cluster2)",
   "type": "stat",
   "description": "$Cluster2: Number of entries per region in descending order. Displays up to top 15 regions.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Total Entries (Primary & Backup) ($Cluster)",
   "type": "stat",
   "description": "$Cluster: Total number of entries in all regions including primary and backup",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries (Primary & Backup) ($Cluster2)",
   "type": "stat",
   "description": "$Cluster2: Total number of entries in all regions including primary and backup",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 12, "w": 6, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 12, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})-sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Members ($Cluster)",
   "type": "table",
   "description": "$Cluster: Member resource statuses",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Member resource statuses",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of entries in each region",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Region Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of entries in each region",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}