{
 "title": "Dual Partitioned Regions Columns",
 "tags": [
  "dual gemfire",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Maps: Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of map entries owned by the member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of map entries owned by the member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of backup entries held by the member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of backup entries held by the member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Memory ($Cluster)",
   "type": "table",
   "description": "$Cluster: Memory cost of owned map entries on this member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Memory ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Memory cost of owned map entries on this member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Memory ($Cluster)",
   "type": "table",
   "description": "$Cluster: Memory cost of owned map entries on this member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Memory ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Memory cost of owned map entries on this member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Merkle Trees Used Heap (WAN) ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total heap cost of the Merkle trees used",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_merkleTreesCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Merkle Trees Used Heap (WAN) ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total heap cost of the Merkle trees used",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_merkleTreesCost{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost ($Cluster)",
   "type": "table",
   "description": "$Cluster: Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_memoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_memoryCost{$ClusterFilterLabel=\"$Cluster2\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Hits ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of reads of the locally owned entries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Hits ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of reads of the locally owned entries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hits{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Events ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of local events received on the map",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Events ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of local events received on the map",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Expirations ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of expirations happened on locally owned entries, backups are not included",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_expirationCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Expirations ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of expirations happened on locally owned entries, backups are not included",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_expirationCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Evictions ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_evictionCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Evictions ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_evictionCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Force Evicted Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of forced evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_forceEvictedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Force Evicted Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of forced evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_forceEvictedEntryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Query Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of queries executed on the map (it may be imprecise for queries involving partition predicates (PartitionPredicate) on the off-heap storage)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Query Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of queries executed on the map (it may be imprecise for queries involving partition predicates (PartitionPredicate) on the off-heap storage)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Indexed Query Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of indexed local queries performed on the map",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Indexed Query Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of indexed local queries performed on the map",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Other Operations ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of other operations performed on this member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Other Operations ($Cluster2)",
   "type": "table",
   "description": "$Cluster2 Total number of other operations performed on this member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Locked Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of locked entries that the member owns",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_lockedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Locked Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of locked entries that the member owns",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_lockedEntryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dirty Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of updated but not persisted yet entries, dirty entries, that the member owns",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_dirtyEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dirty Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of updated but not persisted yet entries, dirty entries, that the member owns",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_dirtyEntryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Map Store: Waiting To Be Processed Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of off loaded map store operations waiting to be processed",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_waitingToBeProcessedCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map.store.offloaded.operations\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Map Store: Waiting To Be Processed Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of off loaded map store operations waiting to be processed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_waitingToBeProcessedCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"map.store.offloaded.operations\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}