{
 "title": "Dual Locators",
 "tags": [
  "dual gemfire",
  "locator",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Jobs ($Cluster)",
   "type": "table",
   "description": "$Cluster: Job status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_submitted{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedSuccessfully{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "Completed Successfully"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedWithFailure{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionStarted{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Jobs ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Job status",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_submitted{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedSuccessfully{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "Completed Successfully"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedWithFailure{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionStarted{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Jobs: Submitted ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of computational jobs submitted",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_submitted{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Submitted ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster: Number of computational jobs submitted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_submitted{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Started ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of computational job executions started. Each job can execute multiple times, for example when it’s restarted or suspended and then resumed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionStarted{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Started ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of computational job executions started. Each job can execute multiple times, for example when it’s restarted or suspended and then resumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionStarted{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed Successfully ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of computational jobs successfully completed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedSuccessfully{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed Successfully ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of computational jobs successfully completed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedSuccessfully{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed with Failure ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of computational jobs that have failed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedWithFailure{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed with Failure ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of computational jobs that have failed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedWithFailure{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Execution Terminated ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of computational job executions finished. Each job can execute multiple times, for example when it’s restarted or suspended and then resumed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionTerminated{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Execution Terminated ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of computational job executions finished. Each job can execute multiple times, for example when it’s restarted or suspended and then resumed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionTerminated{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}