{
 "title": "Dual Clients",
 "tags": [
  "dual gemfire",
  "cluster",
  "client"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients ($Cluster)",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients ($Cluster)",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients ($Cluster2)",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}