{
 "title": "All WAN Replication",
 "tags": [
  "all gemfire",
  "wan",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "GatewaySender",
    "label": "Gateway Sender",
    "query": {
     "query": "label_values(gemfire_eventsQueued{category=\"GatewaySenderStatistics\", $ClusterFilterLabel=~\"$ClusterList\"},exported_instance)"
    }
   },
   {
    "name": "GatewayReceiver",
    "label": "Gateway Receiver",
    "query": {
     "query": "label_values(gemfire_eventsReceived{category=\"GatewayReceiverStatistics\", $ClusterFilterLabel=~\"$ClusterList\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gateway Senders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gateway Senders: Queue Size",
   "type": "timeseries",
   "description": "Size of the event operations queue.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Senders: Secondary Queue Size",
   "type": "timeseries",
   "description": "Size of the secondary event queue.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_secondaryEventQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Senders: Average Batch Distribution Time",
   "type": "timeseries",
   "description": "Average time spent distribution a batch of events.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_batchDistributionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}/gemfire_batchesDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Senders: Average Event Queue Time",
   "type": "timeseries",
   "description": "Average time an event reside in the queue.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_eventQueueTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}/gemfire_eventsDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Senders: Total Unprocessed Events (Aggregate)",
   "type": "timeseries",
   "description": "Total number of gateway sender unprocessed events across the selected gateway senders.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gemfire_unprocessedEventsAddedBySecondary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Added By Secondary"
    },
    {
     "expr": "sum(gemfire_unprocessedEventsRemovedByPrimary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Removed By Primary"
    },
    {
     "expr": "sum(gemfire_unprocessedEventsRemovedByTimeout{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Removed By Timeout"
    },
    {
     "expr": "sum(gemfire_unprocessedTokensAddedByPrimary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Tokens Added By Primary"
    },
    {
     "expr": "sum(gemfire_unprocessedTokensRemovedBySecondary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Tokens Removed By Secondary"
    },
    {
     "expr": "sum(gemfire_unprocessedTokensRemovedByTimeout{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Tokens Removed By Timeout"
    }
   ]
  },
  {
   "title": "Gateway Senders: Total Queue Events (Aggregate)",
   "type": "timeseries",
   "description": "Total number of gateway sender queue events across the selected  gateway senders.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gemfire_eventsQueued{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Queued"
    },
    {
     "expr": "sum(gemfire_eventsFiltered{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Filtered"
    },
    {
     "expr": "sum(gemfire_eventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Received"
    },
    {
     "expr": "sum(gemfire_notQueuedEvent{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Not Queued"
    }
   ]
  },
  {
   "title": "Gateway Senders:  Events - Single Gateway Sender",
   "type": "table",
   "description": "Select gateway sender events. Displays stats of one (1) of gateway senders per member.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventQueueTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDroppedDueToPrimarySenderNotRunning{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsExceedingAlertThreshold{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsFiltered{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalanceTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesCompleted{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_notQueuedEvent{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_secondaryEventQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Senders: Complete Stats - Single Gateway Sender",
   "type": "table",
   "description": "All gateway sender stats. Displays stats of one (1) of gateway senders per member.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_batchDistributionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesRedistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesResized{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesWithIncompleteTransactions{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_conflationIndexesSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsCreated{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsQueued{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaExceptionsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_enqueueFullValueFailedEntryDestroyed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventQueueTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsConflatedFromBatches{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDroppedDueToPrimarySenderNotRunning{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsExceedingAlertThreshold{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsFiltered{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsNotQueuedConflated{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsProcessedByPQRM{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValueEventsCreated{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValueEventsCreatedWithDeltaAvailable{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValueEventsDistributed{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalanceTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesCompleted{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_notQueuedEvent{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_secondaryEventQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_synchronizationEventsEnqueued{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_synchronizationEventsProvided{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tempQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventMapSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventsAddedBySecondary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventsRemovedByPrimary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventsRemovedByTimeout{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokenMapSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokensAddedByPrimary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokensRemovedBySecondary{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokensRemovedByTimeout{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewaySenderStatistics\", exported_instance=~\"$GatewaySender\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gateway Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Gateway Receivers: Events (Aggregate)",
   "type": "timeseries",
   "description": "Total Gateway receiver event stats across the selected  gateway receivers.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_eventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Events Received"
    },
    {
     "expr": "sum(gemfire_createRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Create Requests"
    },
    {
     "expr": "sum(gemfire_updateRequest{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Update Requests"
    },
    {
     "expr": "sum(gemfire_destroyRequest{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Destroy Requests"
    },
    {
     "expr": "sum(gemfire_deltaEventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Delta Events Received"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Message Size (Aggregate)",
   "type": "timeseries",
   "description": "Total region operation events across the selected  gateway receivers.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_messageBytesBeingReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Message Bytes Being Received"
    },
    {
     "expr": "sum(gemfire_receivedBytes{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Received Bytes"
    },
    {
     "expr": "sum(gemfire_sentBytes{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"})",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} Sent Bytes"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Average Batch Process Time",
   "type": "timeseries",
   "description": "Gateway batch process latency",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_processBatchTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"} / gemfire_processBatchResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Load Per Connection",
   "type": "timeseries",
   "description": "Gateway batch process latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Clients",
   "type": "timeseries",
   "description": "Current client connections",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Events - Single Gateway Receiver",
   "type": "table",
   "description": "Select gateway receiver events. Displays stats of one (1) of gateway receivers per member.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_createRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRequest{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateRequest{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsRetried{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_exceptions{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_failedConnectionAttempts{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Complete  - Single Gateway Receiver",
   "type": "table",
   "description": "All gateway receiver stats. Displays stats of one (1) of gateway receivers per member.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_abandonedReadRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_abandonedWriteRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_acceptThreadStarts{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_acceptsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clearRegionRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clearRegionResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_closeConnectionRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionLoad{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionsTimedOut{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_containsKeyRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_containsKeyResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_createRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRegionRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRegionResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRequest{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_duplicateBatchesReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_earlyAcks{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsRetried{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_exceptions{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_failedConnectionAttempts{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValuesRequested{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_invalidateRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_invalidateResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerQueue{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_messageBytesBeingReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_messagesBeingReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_outOfOrderGatewayBatchIds{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_outoforderBatchesReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processBatchRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processBatchResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processBatchTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClearRegionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processCloseConnectionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processContainsKeyTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processDestroyRegionTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processDestroyTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processGetAllTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processGetTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processInvalidateTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processPutAllTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processPutTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processQueryTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processRemoveAllTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processSizeTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queryRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queryResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueInitializationsInProgress{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueLoad{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClearRegionRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readCloseConnectionRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readContainsKeyRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readDestroyRegionRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readDestroyRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readGetAllRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readGetRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readInvalidateRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readProcessBatchRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readPutAllRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readPutRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readQueryRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readRemoveAllRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readSizeRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_receivedBytes{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sentBytes{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sizeRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sizeResponses{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_threadQueueSize{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unknownOperationsReceived{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateRequest{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClearRegionResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeContainsKeyResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeDestroyRegionResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeDestroyResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeGetAllResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeGetResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeInvalidateResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeProcessBatchResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writePutAllResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writePutResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeQueryResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeRemoveAllResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeSizeResponseTime{$ClusterFilterLabel=~\"$ClusterList\", category=\"GatewayReceiverStatistics\", exported_instance=~\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}