{
 "title": "All Partitioned Regions Columns Total Charts",
 "tags": [
  "all gemfire",
  "partitioned region",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitioned Region: Entries",
   "type": "piechart",
   "description": "Total number of primary and backup entries per partitioned region per cluster",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Region: Bytes In Use",
   "type": "piechart",
   "description": "Total amount of data in partitioned regions per cluster",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\", category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Memory",
   "type": "piechart",
   "description": "Total value sizes of primary and backup in bytes per cluster. This does not include keys and entry overheads. ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Average Object Size",
   "type": "piechart",
   "description": "Average object size of partitioned regions in each cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}/gemfire_dataStoreEntryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Entries",
   "type": "barchart",
   "description": "Number of primary and backup entries per member",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Average Object Size",
   "type": "barchart",
   "description": "Average object size of values in partition regions per member",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}/gemfire_dataStoreEntryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Memory",
   "type": "barchart",
   "description": "Value sizes in bytes per member. This does not include keys and entry overheads. ",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Gets",
   "type": "barchart",
   "description": "Number of gets performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Hits",
   "type": "barchart",
   "description": "Number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"} - gemfire_misses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Misses",
   "type": "barchart",
   "description": "Number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Puts",
   "type": "barchart",
   "description": "Number of puts performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_puts{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Cache Updates",
   "type": "barchart",
   "description": "Number of updates performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Creates",
   "type": "barchart",
   "description": "Number of creates performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_creates{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Destroys",
   "type": "barchart",
   "description": "Number of destroys performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_destroys{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Event Threads",
   "type": "barchart",
   "description": "Number of event threads.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventThreads{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Events Queued",
   "type": "barchart",
   "description": "Number of events queued.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Query Executions",
   "type": "barchart",
   "description": "Number of query executions",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: Evictions",
   "type": "barchart",
   "description": "Number of evictions by criteria.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_evictByCriteria_evictions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: TX Rollbacks",
   "type": "barchart",
   "description": "Number of transaction rollbacks.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txRollbacks{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions: TX Failures",
   "type": "barchart",
   "description": "Number of transaction failures.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txFailures{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}