{
 "title": "Dual Disk Stores Columns Charts",
 "tags": [
  "dual gemfire",
  "storage",
  "disk store"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Disk Stores: Queue Size",
   "type": "barchart",
   "description": "$Cluster: Queue size",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Queue Size",
   "type": "barchart",
   "description": "$Cluster2: Queue size",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queueSize{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Writes",
   "type": "barchart",
   "description": "$Cluster: Number of writes to disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_writes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Writes",
   "type": "barchart",
   "description": "$Cluster2: Number of writes to disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_writes{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Written Bytes",
   "type": "barchart",
   "description": "$Cluster: Total amount of data written to data store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_writtenBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Written Bytes",
   "type": "barchart",
   "description": "$Cluster2: Total amount of data written to data store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_writtenBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Write Time",
   "type": "barchart",
   "description": "$Cluster: Write latency",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_writeTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Write Time",
   "type": "barchart",
   "description": "$Cluster2: Write latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_writeTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Reads",
   "type": "barchart",
   "description": "$Cluster: Number of read from disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_reads{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Reads",
   "type": "barchart",
   "description": "$Cluster2: Number of read from disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_reads{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Read Bytes",
   "type": "barchart",
   "description": "$Cluster: Total amount of data read from data store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_readBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Read Bytes",
   "type": "barchart",
   "description": "$Cluster2: Total amount of data read from data store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_readBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Read Time",
   "type": "barchart",
   "description": "$Cluster: Read latency",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_readTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Read Time",
   "type": "barchart",
   "description": "$Cluster2: Read latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_readTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Flushes",
   "type": "barchart",
   "description": "$Cluster: Number of write flushes to disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_flushes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Flushes",
   "type": "barchart",
   "description": "$Cluster2: Number of write flushes to disk store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_flushes{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Flushed Bytes",
   "type": "barchart",
   "description": "$Cluster: Total amount of data flushed to data store.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_flushedBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Flushed Bytes",
   "type": "barchart",
   "description": "$Cluster2: Total amount of data flushed to data store.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_flushedBytes{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Stores: Flush Time",
   "type": "barchart",
   "description": "$Cluster: Flush latency",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_flushTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Stores: Flush Time",
   "type": "barchart",
   "description": "$Cluster2: Flush latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_flushTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DiskStoreStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}