{
 "title": "Dual Search Lucene",
 "tags": [
  "dual gemfire",
  "lucene",
  "compute"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Lucene Indexes Average Query Execution Time",
   "type": "timeseries",
   "description": "$Cluster: Average Lucene query execution latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}/gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes Average Query Execution Time",
   "type": "timeseries",
   "description": "$Cluster: Average Lucene query execution latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}/gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Query Executions",
   "type": "table",
   "description": "$Cluster: The number of Lucene queries executed on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Query Executions",
   "type": "table",
   "description": "$Cluster: The number of Lucene queries executed on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Query Execution Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent executing Lucene queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Query Execution Time",
   "type": "table",
   "description": "$Cluster2: The amount of time spent executing Lucene queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Query Execution Total Hits",
   "type": "table",
   "description": "$Cluster: The total number of documents returned by query executions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTotalHits{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Query Execution Total Hits",
   "type": "table",
   "description": "$Cluster2: The total number of documents returned by query executions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionTotalHits{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Query Executions In Progress",
   "type": "table",
   "description": "$Cluster: The number of query executions currently in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Query Executions In Progress",
   "type": "table",
   "description": "$Cluster2: The number of query executions currently in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutionsInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Commit Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent in Lucene index commits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_commitTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Commit Time",
   "type": "table",
   "description": "$Cluster2: The amount of time spent in Lucene index commits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_commitTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Commits",
   "type": "table",
   "description": "$Cluster: The number of Lucene index commits on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commits{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Commits",
   "type": "table",
   "description": "$Cluster2: The number of Lucene index commits on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commits{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Commits In Progress",
   "type": "table",
   "description": "$Cluster: The number of Lucene index commits in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commitsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Commits In Progress",
   "type": "table",
   "description": "$Cluster2: The number of Lucene index commits in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_commitsInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Documents",
   "type": "table",
   "description": "$Cluster: The number of documents in the index.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_documents{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Documents",
   "type": "table",
   "description": "$Cluster2: The number of documents in the index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_documents{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Failed Entries",
   "type": "table",
   "description": "$Cluster: The number of failed entries for the index.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_failedEntries{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Failed Entries",
   "type": "table",
   "description": "$Cluste2r: The number of failed entries for the index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_failedEntries{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Reindex Repositories",
   "type": "table",
   "description": "$Cluster: The number of reindex repositories.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositories{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Reindex Repositories",
   "type": "table",
   "description": "$Cluster2: The number of reindex repositories.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositories{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Reindex Repositories In Progress",
   "type": "table",
   "description": "$Cluster: The number of reindex repositories in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Reindex Repositories In Progress",
   "type": "table",
   "description": "$Cluster2: The number of reindex repositories in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Reindex Repositories Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent reindexing Lucene repositories.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Reindex Repositories Time",
   "type": "table",
   "description": "$Cluster2: The amount of time spent reindexing Lucene repositories.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexRepositoriesTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Reindexes",
   "type": "table",
   "description": "$Cluster: The number of Lucene reindexes created on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexes{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Reindexes",
   "type": "table",
   "description": "$Cluster2: The number of Lucene reindexes created on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexes{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Reindexes In Progress",
   "type": "table",
   "description": "$Cluster: The number of reindexes currently in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Reindexes In Progress",
   "type": "table",
   "description": "$Cluster2: The number of reindexes currently in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reindexesInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Reindexes Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent reindexing Lucene.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexesTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Reindexes Time",
   "type": "table",
   "description": "$Cluster2: The amount of time spent reindexing Lucene.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_reindexesTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Repository Query Execution Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent executing Lucene repository queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Repository Query Execution Time",
   "type": "table",
   "description": "$Cluster2: The amount of time spent executing Lucene repository queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Repository Query Execution Total Hits",
   "type": "table",
   "description": "$Cluster: The total number of documents returned by repository query executions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTotalHits{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Repository Query Execution Total Hits",
   "type": "table",
   "description": "$Cluster2: The total number of documents returned by repository query executions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionTotalHits{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Repository Query Executions",
   "type": "table",
   "description": "$Cluster: The number of Lucene repository queries executed on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutions{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Repository Query Executions",
   "type": "table",
   "description": "$Cluster2: The number of Lucene repository queries executed on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutions{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Repository Query Executions In Progress",
   "type": "table",
   "description": "$Cluster: The number of repository query executions currently in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Repository Query Executions In Progress",
   "type": "table",
   "description": "$Cluster2: The number of repository query executions currently in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_repositoryQueryExecutionsInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Update Time",
   "type": "table",
   "description": "$Cluster: The amount of time spent adding or removing documents from the index.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Update Time",
   "type": "table",
   "description": "$Cluster2: The amount of time spent adding or removing documents from the index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Updates",
   "type": "table",
   "description": "$Cluster: The number of Lucene index documents added or removed on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Updates",
   "type": "table",
   "description": "$Cluster2: The number of Lucene index documents added or removed on the member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Lucene Indexes: Updates In Progress",
   "type": "table",
   "description": "$Cluster: The number of index updates in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Lucene Indexes: Updates In Progress",
   "type": "table",
   "description": "$Cluster2: The number of index updates in progress.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"LuceneIndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}