{
 "title": "Dual Clients",
 "tags": [
  "dual gemfire",
  "cluster",
  "client"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 11, "x": 12, "y": 0 }
  },
  {
   "title": "Clients ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of client virtual machines (clients) connected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of client virtual machines (clients) connected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Threads ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: The current number of threads dealing with a client connection and the total number of threads created (starts) to deal with a client connection.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}} Threads"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}} Thread Starts"
    }
   ]
  },
  {
   "title": "Connection Threads ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: The current number of threads dealing with a client connection and the total number of threads created (starts) to deal with a client connection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}} Threads"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "{{instance}} Thread Starts"
    }
   ]
  },
  {
   "title": "Clients ($Cluster)",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluste2r\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheServerStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Client Notifier ($Cluster)",
   "type": "table",
   "description": "$Cluster: Statistics regarding cache server operations sent to all clients.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_durableReconnectionCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_events{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsEnqueuedWhileClientAwayCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueDroppedCount{$ClusterFilterLabel=\"$Cluster\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Client Notifier ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Statistics regarding cache server operations sent to all clients.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientHealthMonitorRegister{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientHealthMonitorUnRegister{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrationTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRegistrations{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqProcessingTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_durableReconnectionCount{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventProcessingTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_events{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsEnqueuedWhileClientAwayCount{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueDroppedCount{$ClusterFilterLabel=\"$Cluster2\", category=\"CacheClientNotifierStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients ($Cluster)",
   "type": "table",
   "description": "$Cluster: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$Cluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LocatorStats: Clients ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Client connections and activities overview",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=\"$Cluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}