{
 "title": "Dual Indexes",
 "tags": [
  "dual gemfire",
  "dual compute",
  "dual indexes",
  "indexes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  { "title": "Index Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$Cluster: Index Stats: Bucket Indexes",
   "type": "table",
   "description": "$Cluster: Number of bucket indexes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numBucketIndexes{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Bucket Indexes",
   "type": "table",
   "description": "$Cluster2: Number of bucket indexes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numBucketIndexes{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Keys",
   "type": "table",
   "description": "$Cluster: Number of keys.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numKeys{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Keys",
   "type": "table",
   "description": "$Cluster2: Number of keys.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numKeys{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Map Index Keys",
   "type": "table",
   "description": "$Cluster: Number of map index keys.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numMapIndexKeys{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Map Index Keys",
   "type": "table",
   "description": "$Cluster2: Number of map index keys.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numMapIndexKeys{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Updates",
   "type": "table",
   "description": "$Cluster: Number of updates.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numUpdates{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Updates",
   "type": "table",
   "description": "$Cluster2: Number of updates.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numUpdates{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Uses",
   "type": "table",
   "description": "$Cluster: Number of uses.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numUses{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Uses",
   "type": "table",
   "description": "$Cluster2: Number of uses.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numUses{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Values",
   "type": "table",
   "description": "$Cluster: Number of values.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numValues{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Values",
   "type": "table",
   "description": "$Cluster2: Number of values.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_numValues{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Read Lock Count",
   "type": "table",
   "description": "$Cluster: Number of read locks.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_readLockCount{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Read Lock Count",
   "type": "table",
   "description": "$Cluster2: Number of read locks.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_readLockCount{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Update Time",
   "type": "table",
   "description": "$Cluster: Update time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Update Time",
   "type": "table",
   "description": "$Cluster2: Update time.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_updateTime{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Updates in Progress",
   "type": "table",
   "description": "$Cluster: Number of updates in progress.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Updates in Progress",
   "type": "table",
   "description": "$Cluster2: Number of updates in progress.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_updatesInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Use Time",
   "type": "table",
   "description": "$Cluster: Use time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_useTime{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Use Time",
   "type": "table",
   "description": "$Cluster2: Use time.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_useTime{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Stats: Uses in Progress",
   "type": "table",
   "description": "$Cluster: Number uses in progress.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_usesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Stats: Uses in Progress",
   "type": "table",
   "description": "$Cluster2: Number uses in progress.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_usesInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"IndexStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Index Status per Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "$Cluster: Index Initialization Completed",
   "type": "table",
   "description": "$Cluster: Number of index initialization completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Initialization Completed",
   "type": "table",
   "description": "$Cluster2: Number of index initialization completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationCompleted{$ClusterFilterLabel=\"$Cluster2\", category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Initialization in Progress",
   "type": "table",
   "description": "$Cluster: Number of index initialization in progress.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Initialization in Progress",
   "type": "table",
   "description": "$Cluster2: Number of index initialization in progress.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Initialization Time",
   "type": "table",
   "description": "$Cluster: Index initialization latency",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationTime{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Initialization Time",
   "type": "table",
   "description": "$Cluster2: Index initialization latency",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_indexInitializationTime{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Update Completed",
   "type": "table",
   "description": "$Cluster: Number of index updates completed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Update Completed",
   "type": "table",
   "description": "$Cluster2: Number of index updates completed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Update in Progress",
   "type": "table",
   "description": "$Cluster: Number of index updates in progress",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Update in Progress",
   "type": "table",
   "description": "$Cluster2: Number of index updates in progress",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Index Update Time",
   "type": "table",
   "description": "$Cluster: Index update latency",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateTime{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Index Update Time",
   "type": "table",
   "description": "$Cluster2: Index update latency",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_indexUpdateTime{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}