{
 "title": "Dual Partitioned Regions Query Charts",
 "tags": [
  "dual gemfire",
  "query",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Query Executions",
   "type": "barchart",
   "description": "$Cluster: Number of queries executed on the region.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Query Executions",
   "type": "barchart",
   "description": "$Cluster2: Number of queries executed on the region.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Region Query Count (aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Number of queries executed performed on all regions",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\",member_type=\"server\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(gemfire_queryRequests{$ClusterFilterLabel=\"$Cluster\",category=\"CacheServerStats\",member_type=\"server\"})",
     "legendFormat": "Query Requests"
    },
    {
     "expr": "sum(gemfire_queryResponses{$ClusterFilterLabel=\"$Cluster\",category=\"CacheServerStats\",member_type=\"server\"})",
     "legendFormat": "Query Responses"
    },
    {
     "expr": "sum(gemfire_partitionedRegionQueryRetries{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\",member_type=\"server\"})",
     "legendFormat": "Query Retries"
    },
    {
     "expr": "sum(gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster\",category=\"CacheClientNotifierStatistics\",member_type=\"server\"})",
     "legendFormat": "Compiled Query Count"
    },
    {
     "expr": "sum(gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster\",category=\"CacheClientNotifierStatistics\",member_type=\"server\"})",
     "legendFormat": "Compiled Query Used Count"
    }
   ]
  },
  {
   "title": "$Cluster2: Region Query Count (aggregate)",
   "type": "timeseries",
   "description": "$Cluster2: Number of queries executed performed on all regions",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\",member_type=\"server\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(gemfire_queryRequests{$ClusterFilterLabel=\"$Cluster2\",category=\"CacheServerStats\",member_type=\"server\"})",
     "legendFormat": "Query Requests"
    },
    {
     "expr": "sum(gemfire_queryResponses{$ClusterFilterLabel=\"$Cluster2\",category=\"CacheServerStats\",member_type=\"server\"})",
     "legendFormat": "Query Responses"
    },
    {
     "expr": "sum(gemfire_partitionedRegionQueryRetries{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\",member_type=\"server\"})",
     "legendFormat": "Query Retries"
    },
    {
     "expr": "sum(gemfire_compiledQueryCount{$ClusterFilterLabel=\"$Cluster2\",category=\"CacheClientNotifierStatistics\",member_type=\"server\"})",
     "legendFormat": "Compiled Query Count"
    },
    {
     "expr": "sum(gemfire_compiledQueryUsedCount{$ClusterFilterLabel=\"$Cluster2\",category=\"CacheClientNotifierStatistics\",member_type=\"server\"})",
     "legendFormat": "Compiled Query Used Count"
    }
   ]
  },
  {
   "title": "$Cluster: CQ Query (aggregate)",
   "type": "timeseries",
   "description": "$Cluster: CQ query execution stats",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Executions Completed"
    },
    {
     "expr": "sum(gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Execution In Progress"
    },
    {
     "expr": "sum(gemfire_numUniqueCqQuery{$ClusterFilterLabel=\"$Cluster\",category=\"CqServiceStats\"})",
     "legendFormat": "Unique Query Count"
    }
   ]
  },
  {
   "title": "$Cluster2: CQ Query (aggregate)",
   "type": "timeseries",
   "description": "$Cluster2: CQ query execution stats",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Executions Completed"
    },
    {
     "expr": "sum(gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Execution In Progress"
    },
    {
     "expr": "sum(gemfire_numUniqueCqQuery{$ClusterFilterLabel=\"$Cluster2\",category=\"CqServiceStats\"})",
     "legendFormat": "Unique Query Count"
    }
   ]
  }
 ]
}