{
 "title": "Dual Partitioned Regions Columns Charts",
 "tags": [
  "dual gemfire",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Partitioned Regions: Entries",
   "type": "barchart",
   "description": "$Cluster: Number of primary entries per member",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Entries",
   "type": "barchart",
   "description": "$Cluster2: Number of primary entries per member",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Backup Entries",
   "type": "barchart",
   "description": "$Cluster: Number of backup entries per member (custom stats)",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsSize{$ClusterFilterLabel=\"$Cluster\", category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Backup Entries",
   "type": "barchart",
   "description": "$Cluster2: Number of backup entries per member (custom stats)",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsSize{$ClusterFilterLabel=\"$Cluster2\", category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Primary Memory",
   "type": "barchart",
   "description": "$Cluster: Primary value sizes in bytes per member. This does not include keys and entry overheads. ",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Primary Memory",
   "type": "barchart",
   "description": "$Cluster2: Primary value sizes in bytes per member. This does not include keys and entry overheads. ",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Average Object Size",
   "type": "barchart",
   "description": "$Cluster: Average object size in each member's partition region",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}/gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Average Object Size",
   "type": "barchart",
   "description": "$Cluster2: Average object size in each member's partition region",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\"}/gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Cache Hits",
   "type": "barchart",
   "description": "$Cluster: Number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"} - gemfire_misses{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Cache Hits",
   "type": "barchart",
   "description": "$Cluster2: Number of times a get on the cache did find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"} - gemfire_misses{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Cache Misses",
   "type": "barchart",
   "description": "$Cluster: Number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Cache Misses",
   "type": "barchart",
   "description": "$Cluster2: Number of times a get on the cache did not find a value already in local memory.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_misses{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Cache Updates",
   "type": "barchart",
   "description": "$Cluster: Number of updates performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Cache Updates",
   "type": "barchart",
   "description": "$Cluster2: Number of updates performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_updates{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Puts",
   "type": "barchart",
   "description": "$Cluster: Number of puts performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_puts{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Puts",
   "type": "barchart",
   "description": "$Cluster2: Number of puts performed on the region.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_puts{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Gets",
   "type": "barchart",
   "description": "$Cluster: Number of gets performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Gets",
   "type": "barchart",
   "description": "$Cluster2: Number of gets performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_gets{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Destroys",
   "type": "barchart",
   "description": "$Cluster: Number of destroys performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_destroys{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Destroys",
   "type": "barchart",
   "description": "$Cluster2: Number of destroys performed on the region.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_destroys{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Event Threads",
   "type": "barchart",
   "description": "$Cluster: Number of event threads.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventThreads{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Event Threads",
   "type": "barchart",
   "description": "$Cluster2: Number of event threads.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventThreads{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Events Queued",
   "type": "barchart",
   "description": "$Cluster: Number of events queued.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Events Queued",
   "type": "barchart",
   "description": "$Cluster2: Number of events queued.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Query Executions",
   "type": "barchart",
   "description": "$Cluster: Number of query executions",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Query Executions",
   "type": "barchart",
   "description": "$Cluster2: Number of query executions",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Evictions",
   "type": "barchart",
   "description": "$Cluster: Number of evictions by criteria.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_evictByCriteria_evictions{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Evictions",
   "type": "barchart",
   "description": "$Cluster2: Number of evictions by criteria.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_evictByCriteria_evictions{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: TX Rollbacks",
   "type": "barchart",
   "description": "$Cluster: Number of transaction rollbacks.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txRollbacks{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: TX Rollbacks",
   "type": "barchart",
   "description": "$Cluster2: Number of transaction rollbacks.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txRollbacks{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: TX Failures",
   "type": "barchart",
   "description": "$Cluster: Number of transaction failures.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txFailures{$ClusterFilterLabel=\"$Cluster\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: TX Failures",
   "type": "barchart",
   "description": "$Cluster2: Number of transaction failures.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_txFailures{$ClusterFilterLabel=\"$Cluster2\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}