{
 "title": "Dual Partitions",
 "tags": [
  "dual gemfire",
  "dual partitions",
  "partitions",
  "distribution"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Partitioned Region Queue Size",
   "type": "timeseries",
   "description": "$Cluster: Number of events in the partitioned region queue.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Region Queue Size",
   "type": "timeseries",
   "description": "$Cluster2: Number of events in the partitioned region queue.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueueSize{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Primary Buckets",
   "type": "barchart",
   "description": "$Cluster: Number of primary entries per member",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Primary Buckets",
   "type": "barchart",
   "description": "$Cluster2: Number of primary entries per member",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Redundant Buckets",
   "type": "barchart",
   "description": "$Cluster: Number of redundant buckets per partitioned region (Mastercard custom stats).",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsCount{$ClusterFilterLabel=\"$Cluster\",category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Redundant Buckets",
   "type": "barchart",
   "description": "$Cluster2: Number of redundant buckets per partitioned region (Mastercard custom stats).",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsCount{$ClusterFilterLabel=\"$Cluster2\",category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Region Queues, Threads",
   "type": "table",
   "description": "$Cluster: Partitioned region queue and thread stats",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionQueueThrottleCount{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionQueueThrottleTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadStarts{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreads{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Region Queues, Threads",
   "type": "table",
   "description": "$Cluster2: Partitioned region queue and thread stats",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_partitionedRegionQueueSize{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionQueueThrottleCount{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionQueueThrottleTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadJobs{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreadStarts{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_partitionedRegionThreads{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Primary Buckets",
   "type": "table",
   "description": "$Cluster: Number of primary buckets per partitioned region.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Primary Buckets",
   "type": "table",
   "description": "$Cluster2: Number of primary buckets per partitioned region.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions: Redundant Buckets",
   "type": "table",
   "description": "$Cluster: Number of backup buckets per partitioned region (Mastercard custom stats).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsCount{$ClusterFilterLabel=\"$Cluster\",category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions: Redundant Buckets",
   "type": "table",
   "description": "$Cluster2: Number of backup buckets per partitioned region (Mastercard custom stats).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_redundantBucketsCount{$ClusterFilterLabel=\"$Cluster2\",category=\"McPartitionedRegionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}