{
 "title": "Partitions",
 "tags": [
  "gemfire",
  "partition"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Partitioned Region: Bucket Count",
   "type": "table",
   "description": "$Cluster: Number of partitioned region buckets per member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_totalNumBuckets{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "gemfire_primaryBucketCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Member Partitions",
   "type": "table",
   "description": "$Cluster: Partition status across all members",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_completedMigrations{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_activePartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_replicaSyncRequestsCounter{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_replicaSyncSemaphore{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_stateStamp{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalCompletedMigrations{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalElapsedDestinationCommitTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalElapsedMigrationOperationTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalElapsedMigrationTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_runningPartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_publicationCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"event\",tag0=\"\\\"service=hz:core:partitionService\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_executedOperationsCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.partition\",tag0=~\".*partitionId=.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Partition Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Partition Threads: Error Count",
   "type": "table",
   "description": "$Cluster: Total number of failed tasks on this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_errorCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Normal Pending Count",
   "type": "table",
   "description": "$Cluster: Number of normal pending operations (tasks)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_normalPendingCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Priority Pending Count",
   "type": "table",
   "description": "$Cluster: Number of priority pending operations (tasks)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_priorityPendingCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Total Count",
   "type": "table",
   "description": "$Cluster: Total number of tasks (Operation + PartitionSpecificRunnable + Runnable + TaskBatch) completed on this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedTotalCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Operation Count",
   "type": "table",
   "description": "$Cluster: Number of completed operations by this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedOperationCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Operation Batch Count",
   "type": "table",
   "description": "$Cluster: Number of completed TaskBatch (a batch of tasks) by this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedOperationBatchCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Runnable Count",
   "type": "table",
   "description": "$Cluster: Total number of runnables executed by this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedRunnableCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Partition Specific Runnable Count",
   "type": "table",
   "description": "$Cluster: Number of PartitionSpecificRunnable tasks executed by this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedPartitionSpecificRunnableCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Packet Count",
   "type": "table",
   "description": "$Cluster: Number of packets that executed by this operation thread",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedPacketCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}