{
 "title": "All Partitioned Regions Columns Total Charts",
 "tags": [
  "all gemfire",
  "partitioned region",
  "storage"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Cluster3", "label": "Cluster 3", "query": "wan1" },
   { "name": "Cluster4", "label": "Cluster 4", "query": "wan2" }
  ]
 },
 "panels": [
  {
   "title": "Maps: Entries",
   "type": "barchart",
   "description": "Number of map entries owned by the member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Entries",
   "type": "barchart",
   "description": "Number of backup entries held by the member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Memory",
   "type": "barchart",
   "description": "Memory cost of owned map entries on this member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Memory",
   "type": "barchart",
   "description": "Memory cost of backup map entries on this member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Merkle Trees Used Heap (WAN)",
   "type": "barchart",
   "description": "Total heap cost of the Merkle trees used",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_merkleTreesCost{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost",
   "type": "barchart",
   "description": "Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_memoryCost{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Hits",
   "type": "barchart",
   "description": "Number of reads of the locally owned entries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hits{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Events",
   "type": "barchart",
   "description": "Number of local events received on the map",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Expirations",
   "type": "barchart",
   "description": "Number of expirations happened on locally owned entries, backups are not included",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_expirationCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Evictions",
   "type": "barchart",
   "description": "Number of evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_evictionCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Force Evicted Entries",
   "type": "barchart",
   "description": "Number of forced evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_forceEvictedEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Query Count",
   "type": "barchart",
   "description": "Number of queries executed on the map (it may be imprecise for queries involving partition predicates (PartitionPredicate) on the off-heap storage)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Indexed Query Count",
   "type": "barchart",
   "description": "Total number of indexed local queries performed on the map",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Other Operations",
   "type": "barchart",
   "description": "Total number of other operations performed on this member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Locked Entries",
   "type": "barchart",
   "description": "Number of locked entries that the member owns",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_lockedEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dirty Entries",
   "type": "barchart",
   "description": "Number of updated but not persisted yet entries, dirty entries, that the member owns",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_dirtyEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Map Store: Waiting To Be Processed Count",
   "type": "barchart",
   "description": "Number of off loaded map store operations waiting to be processed",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_waitingToBeProcessedCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"map.store.offloaded.operations\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}