{
 "title": "All Locators",
 "tags": [
  "all gemfire",
  "locator",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Jobs",
   "type": "table",
   "description": "Job status",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_submitted{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedSuccessfully{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "Completed Successfully"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedWithFailure{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionStarted{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Jobs: Submitted",
   "type": "timeseries",
   "description": "Number of computational jobs submitted",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_submitted{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Started",
   "type": "timeseries",
   "description": "Number of computational job executions started. Each job can execute multiple times, for example when it’s restarted or suspended and then resumed",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionStarted{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed Successfully",
   "type": "timeseries",
   "description": "Number of computational jobs successfully completed.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedSuccessfully{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed with Failure",
   "type": "timeseries",
   "description": "Number of computational jobs that have failed",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_completedWithFailure{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Execution Terminated",
   "type": "timeseries",
   "description": "Number of computational job executions finished. Each job can execute multiple times, for example when it’s restarted or suspended and then resumed.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "com_gemfire_jet_Metrics_jobs_executionTerminated{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  }
 ]
}