{
 "title": "All Partitioned Regions Query Charts",
 "tags": [
  "all gemfire",
  "query",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Maps: Query Count",
   "type": "timeseries",
   "description": "Number of local queries performed on all maps",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{instance}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Maps: Indexed Query Count",
   "type": "timeseries",
   "description": "Number of indexed local queries performed on all maps. Compare with the Query Count chart and look for queries that are not indexed with high counts. By properly indexing, you can increase query performance. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map\"}",
     "legendFormat": "{{instance}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Indexes: Insert Count",
   "type": "barchart",
   "description": "Number of insert operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_insertCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Insert Latency",
   "type": "barchart",
   "description": "Total latency of insert operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalInsertLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Update Count",
   "type": "barchart",
   "description": "Number of update operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_updateCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Update Latency",
   "type": "barchart",
   "description": "Total latency of update operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalUpdateLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Remove Count",
   "type": "barchart",
   "description": "Number of remove operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Remove Latency",
   "type": "barchart",
   "description": "Total latency of remove operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalRemoveLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Count",
   "type": "barchart",
   "description": "Total number of index hits (the value of this metric may be greater than the map.index.queryCount since a single query may hit the same index more than once)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hitCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Query Count",
   "type": "barchart",
   "description": "Total number of queries served by the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Aveage Hit Selectivity",
   "type": "barchart",
   "description": "Average selectivity of the hits served by the index on this member (the returned value is in the range from 0.0 to 1.0 - values close to 1.0 indicate a high selectivity meaning the index is efficient; values close to 0.0 indicate a low selectivity meaning the index efficiency is approaching an efficiency of a simple full scan)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_averageHitSelectivity{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost",
   "type": "barchart",
   "description": "Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_memoryCost{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}