{
 "title": "All Partitions",
 "tags": [
  "all gemfire",
  "partition"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Member Partitions",
   "type": "table",
   "description": "Partition status across all members in all clusters",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_localPartitionCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_completedMigrations{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_activePartitionCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_replicaSyncRequestsCounter{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_replicaSyncSemaphore{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_stateStamp{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalCompletedMigrations{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalElapsedDestinationCommitTime{$ClusterFilterLabel=~\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalElapsedMigrationOperationTime{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_totalElapsedMigrationTime{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_runningPartitionCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_publicationCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"event\",tag0=\"\\\"job=hz:core:partitionService\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_executedOperationsCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.partition\",tag0=~\".*partitionId=.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Partition Threads: Error Count",
   "type": "table",
   "description": "Total number of tasks (Operation + PartitionSpecificRunnable + Runnable + TaskBatch) completed on this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_errorCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Normal Pending Count",
   "type": "table",
   "description": "Number of normal pending operations (tasks)",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_normalPendingCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Priority Pending Count",
   "type": "table",
   "description": "Number of priority pending operations (tasks)",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_priorityPendingCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Total Count",
   "type": "table",
   "description": "Total number of tasks (Operation + PartitionSpecificRunnable + Runnable + TaskBatch) completed on this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedTotalCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Operation Count",
   "type": "table",
   "description": "Number of completed operations by this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedOperationCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Operation Batch Count",
   "type": "table",
   "description": "Number of completed TaskBatch (a batch of tasks) by this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedOperationBatchCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Runnable Count",
   "type": "table",
   "description": "Total number of runnables executed by this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedRunnableCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Partition Specific Runnable Count",
   "type": "table",
   "description": "Number of PartitionSpecificRunnable tasks executed by this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedPartitionSpecificRunnableCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Packet Count",
   "type": "table",
   "description": "Number of packets that executed by this operation thread",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_completedPacketCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}