global:
  scrape_interval:     5s
  external_labels:
    monitor: 'gemfire'

scrape_configs:
  - job_name: 'locator-mygemfire1'
    file_sd_configs:
      - files:
        - locator-mygemfire1-targets.yml
  - job_name: 'mygemfire1'
    file_sd_configs:
      - files:
        - mygemfire1-targets.yml

  - job_name: 'locator-mygemfire2'
    file_sd_configs:
      - files:
        - locator-mygemfire2-targets.yml
  - job_name: 'mygemfire2'
    file_sd_configs:
      - files:
        - mygemfire2-targets.yml

  - job_name: 'locator-mygemfire3'
    file_sd_configs:
      - files:
        - locator-mygemfire3-targets.yml
  - job_name: 'mygemfire3'
    file_sd_configs:
      - files:
        - mygemfire3-targets.yml
