- targets: [HOST-ADDRESS:8791, HOST-ADDRESS:8792, HOST-ADDRESS:8793, HOST-ADDRESS:8794, HOST-ADDRESS:8795, HOST-ADDRESS:8796, HOST-ADDRESS:8797, HOST-ADDRESS:8798, HOST-ADDRESS:8799]
  labels:
    member_type: 'server'
