{
 "title": "00Main All",
 "tags": [
  "all gemfire",
  "all main"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterServers",
    "label": "ClusterServers",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Main Dashboard",
   "type": "text",
   "description": "The main dashboard of PadoGrid GemFire Dashboards (PHD) that resembles the main dashboard of GemFire Management Center (HMC). PHD includes additional metrics that are not available in HMC and vice versa. PHD exposes a finer degree of individual metric details along with federated cluster views making it more suitable for monitoring production systems.",
   "gridPos": { "h": 43, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "## Main\n\n- [Main Dashboard](/d/ed5d1905-d13d-446a-83d5-3d33d3aadddc/00main?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Dual Main Dashboard](/d/2f6503d9-5b23-4af6-9a87-08f799229df5/00dual-main?var-DataSource=$DataSource&var-Cluster=$Cluster&var-Cluster2=$Cluster2&${__url_time_range})\n- [All Main Dashboard](/d/5a076038-1d97-4c44-abe7-26020351d90b/00main-all?${__url_time_range})\n\n## Cluster\n\n- [All Clients](/d/33010967-1a38-40ac-809d-0fb27836a077/all-client?var-DataSource=$DataSource&${__url_time_range})\n- [All Members](/d/f3f34354-3951-4622-9c20-d2929faf0cd7/all-members?var-DataSource=$DataSource&${__url_time_range})\n- [All Locators](/d/c969a8f0-8f88-4a24-a03a-146c816cb936/all-jet?var-DataSource=$DataSource&${__url_time_range})\n- [All WAN Replication](/d/f0767d64-069b-43e1-9040-a5041bc6e22f/all-wan-replication?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Storage\n\n- [All Regions](/d/e4fdd34f-e420-41f3-986c-d362832a5949/all-partitioned-regions-rows?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Total Charts](/d/ebf72f09-701d-43bc-9ae3-4742b98ff98a/all-partitioned-regions-columns-total-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Total Tables](/d/f0c94184-7607-483a-9940-136a0164f7af/all-partitioned-regions-columns-total?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Charts](/d/72c263e2-3c66-4934-8ce4-2bf6164a168c/all-partitioned-regions-rows-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Tables](/d/e4fdd34f-e420-41f3-986c-d362832a5949/all-partitioned-regions-rows?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Total Charts](/d/80663561-288c-4365-8e95-7520362360d6/all-partitioned-regions-rows-total-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Total Tables](/d/fbac197a-c32c-4a8b-b50c-f02bbed12b43/all-partitioned-regions-rows-total?var-DataSource=$DataSource&${__url_time_range})\n   - [Query Charts](/d/b6e67a00-2463-4e0b-a3e9-da1f6e98776b/all-partitioned-regions-query-charts?var-DataSource=$DataSource&{__url_time_range})\n   - [Query Tables](/d/a2183fa4-a52e-41ee-902b-7a593877e632/all-partitioned-regions-query-tables?var-DataSource=$DataSource&${__url_time_range})\n- [All Replicated Regions](/d/aa215981-9b90-4de9-8b21-79e2e1f9f24c/all-replicated-regions-rows?var-DataSource=$DataSource&${__url_time_range})\n    - [Column Charts](/d/bdb0048b-6553-4f6b-9cfb-4a2ee6e2aa7b/all-replicated-regions-columns-charts?var-DataSource=$DataSource&${__url_time_range})\n    - [Column Tables](/d/04f91208-2512-4a63-a1c8-1c2417fa000e/all-replicated-regions-columns?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Charts](/d/56fe5565-a3c5-4da3-b310-f2b86940792d/all-replicated-regions-rows-charts?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Tables](/d/aa215981-9b90-4de9-8b21-79e2e1f9f24c/all-replicated-regions-rows?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Max Charts](/d/5137780e-fbf6-40b6-af7a-a93090f097a2/all-replicated-regions-rows-max-charts?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Max Tables](/d/b44af92c-658d-4826-bbd9-b39357e4b13d/all-replicated-regions-rows-max?var-DataSource=$DataSource&${__url_time_range})\n- [All Disk Stores](/d/c56e78d3-d79f-4796-bb28-38015c1bbd58/all-disk-stores-rows?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Charts](/d/e9b6c359-7fe0-4fb5-9730-7ea478785359/all-disk-stores-columns-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Tables](/d/4e3b1ad3-7593-41d3-83c6-2a327494ee09/all-disk-stores-columns?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Charts](/d/e7cf9a5a-e977-47d5-aa41-9c408365fab7/all-disk-stores-rows-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Tables](/d/c56e78d3-d79f-4796-bb28-38015c1bbd58/all-disk-stores-rows?var-DataSource=$DataSource&${__url_time_range})\n\n## Partition\n\n- [All Partitions](/d/856cd07b-7fb9-4d1f-a4a7-e311d1dad051/all-partitions?var-DataSource=$DataSource&${__url_time_range})\n\n## Compute\n\n- [All Functions](/d/98bf9d66-e0d8-4e99-986c-aeab6543209f/all-functions?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [All Lucene](/d/d28731c2-21aa-4b65-bde9-cca8e361eceb/all-lucene?var-DataSource=$DataSource&${__url_time_range})\n- [All Indexes](/d/c5acf16d-f374-4671-aa98-bd0d67d70cd6/all-indexes?var-DataSource=$DataSource&${__url_time_range})\n- [All PDX](/d/19345010-412e-41a1-9657-8f4dee84688e/all-pdx?var-DataSource=$DataSource&${__url_time_range})\n\n## Messaging\n\n- [All Async Queues](/d/de00bd57-7333-4bf4-8a42-86d28780972d/all-async-queues?var-DataSource=$DataSource&${__url_time_range})\n- [All CQ](/d/e5ba602a-6607-4b95-b36e-767006172318/all-cq?var-DataSource=$DataSource&&${__url_time_range})\n- [All Distribution](/d/e7097b82-c587-4d41-88a7-f1654946df1d/all-distribution?var-DataSource=$DataSource&${__url_time_range})\n- [All Distributed Locks](/d/045877f2-d1bf-4360-aa57-f5055a73d79f/all-distributed-locks?var-DataSource=$DataSource&${__url_time_range})\n\n## Linux\n\n- [All Linux Systems](/d/0d390247-286d-487f-bd6c-7d486830cd41/all-linux-systems?var-DataSource=$DataSource&${__url_time_range})\n\n"
   }
  },
  {
   "title": "Members: Up Time",
   "type": "stat",
   "description": "Cluster up time determined by the oldest member",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gemfire_process_uptime_seconds{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members: Count",
   "type": "stat",
   "description": "Number of running data nodes in the cluster excluding locators",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_nodes{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "bargauge",
   "description": "Sum of used memory of all members per cluster",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"($ClusterList)\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "bargauge",
   "description": "Sum of free memory of all members per cluster",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"($ClusterList)\",category=\"VMMemoryUsageStats\"}-gemfire_usedMemory{$ClusterFilterLabel=~\"($ClusterList)\",category=\"VMMemoryUsageStats\", exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Up Time",
   "type": "stat",
   "description": "Cluster up time determined by the oldest member",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gemfire_process_uptime_seconds{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locators: Count",
   "type": "stat",
   "description": "Number of running locators",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"locator\"} + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Heap: Used, Max",
   "type": "timeseries",
   "description": "Used vs. Max heap of each member. For sustained performance, keep used heap below 80% of max heap",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "Used {{$ClusterFilterLabel}} {{instance}}"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "Max {{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "Max System CPU Load",
   "type": "timeseries",
   "description": "CPU load of each member across all clusters",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "CPU {{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "System resource status of each member across all clusters",
   "gridPos": { "h": 24, "w": 21, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collectiongemfire_collections_seconds_count{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}