{
 "title": "All Disk Stores Rows",
 "tags": [
  "all gemfire",
  "storage",
  "disk store"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All Replicated Maps Rows Total",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "*This dashboard displays replicated maps for all members in all clusters.*"
   }
  },
  {
   "title": "Multi Maps: Entries",
   "type": "table",
   "description": "Number of multimap entries owned by the member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Backup Entries",
   "type": "table",
   "description": "Number of backup entries held by the member",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Entry Memory",
   "type": "table",
   "description": "Memory cost of owned multimap entries on this member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Backup Memory",
   "type": "table",
   "description": "Memory cost of backup entries in this member",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_backupEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Hits",
   "type": "table",
   "description": "Number of hits (reads) of the locally owned entries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_hits{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Events",
   "type": "table",
   "description": "Number of local events received",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Expirations",
   "type": "table",
   "description": "Number of expirations happened on locally owned entries, backups are not included",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_expirationCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Evictions",
   "type": "table",
   "description": "Number of evictions happened on locally owned entries, backups are not included",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_evictionCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Query Count",
   "type": "table",
   "description": "Number of local queries executed on the multimap (it may be imprecise for queries involving partition predicates (PartitionPredicate) on the off-heap storage)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Indexed Query Count",
   "type": "table",
   "description": "Total number of indexed local queries performed on the multimap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_indexedQueryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Other Operations",
   "type": "table",
   "description": "Total number of other operations performed on this member",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps:  Merkle Trees Used Heap (WAN)",
   "type": "table",
   "description": "Total heap cost of the Merkle trees used",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_merkleTreesCost{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Locked Entries",
   "type": "table",
   "description": "Number of locked entries that the member owns",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_lockedEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Dirty Entries",
   "type": "table",
   "description": "Number of updated but not persisted yet entries, dirty entries, that the member owns",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_dirtyEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Put Count",
   "type": "table",
   "description": "Number of local put operations on the multimap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_putCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Set Count",
   "type": "table",
   "description": "Number of local set operations on the multimap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_setCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Get Count",
   "type": "table",
   "description": "Number of local get operations on the multimap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_getCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Remove Count",
   "type": "table",
   "description": "Number of local remove operations on the multimap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_removeCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Max Put Latency",
   "type": "table",
   "description": "Maximum latency of local put operations",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalMaxPutLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Max Set Latency",
   "type": "table",
   "description": "Maximum latency of local set operations",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalMaxSetLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Max Get Latency",
   "type": "table",
   "description": "Maximum latency of local get operations",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalMaxGetLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Max Remove Latency",
   "type": "table",
   "description": "Maximum latency of local remove operations",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_totalMaxRemoveLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}