{
 "title": "All Async Queues",
 "tags": [
  "all gemfire",
  "async queue",
  "messaging"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Queues",
   "type": "table",
   "description": "Queue status",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedItemCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_backupItemCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_maxAge{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_minAge{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_averageAge{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfOffers{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfPolls{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Items",
   "type": "barchart",
   "description": "Number of owned and backup items in this member",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_ownedItemCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_backupItemCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Age",
   "type": "barchart",
   "description": "Min, max, and average age of the items ",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_maxAge{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_minAge{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_averageAge{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Operations",
   "type": "barchart",
   "description": "Number of operations",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfOffers{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfPolls{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_total{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfOtherOperations{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_gemfire_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Events",
   "type": "timeseries",
   "description": "Number of event operations (duplicate of eventOperationCount)",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_gemfire_Metrics_numberOfEvents{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"queue\"}",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  }
 ]
}