{
 "title": "Dual Memory LRU",
 "tags": [
  "dual gemfire",
  "memory lru",
  "dual memory lru",
  "distribution"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Memory LRU Regions: Byte Count",
   "type": "barchart",
   "description": "$Cluster: Number of bytes in region.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_byteCount{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Byte Count",
   "type": "barchart",
   "description": "$Cluste2r: Number of bytes in region.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_byteCount{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Destroys",
   "type": "barchart",
   "description": "$Cluster: Number of entry destroys triggered by LRU.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Destroys",
   "type": "barchart",
   "description": "$Cluster2: Number of entry destroys triggered by LRU.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Byte Count",
   "type": "table",
   "description": "$Cluster: Number of bytes in region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_byteCount{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Byte Count",
   "type": "table",
   "description": "$Cluste2r: Number of bytes in region.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_byteCount{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Bytes Allowed",
   "type": "table",
   "description": "$Cluster: Total number of bytes allowed in this region.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_bytesAllowed{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Bytes Allowed",
   "type": "table",
   "description": "$Cluster2: Total number of bytes allowed in this region.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_bytesAllowed{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Destroys",
   "type": "table",
   "description": "$Cluster: Number of entry destroys triggered by LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Destroys",
   "type": "table",
   "description": "$Cluster2: Number of entry destroys triggered by LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Evaluations",
   "type": "table",
   "description": "$Cluster: Number of entries evaluated during LRU operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Evaluations",
   "type": "table",
   "description": "$Cluster:2 Number of entries evaluated during LRU operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Evictions",
   "type": "table",
   "description": "$Cluster: Total number of entry evictions triggered by LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvictions{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Evictions",
   "type": "table",
   "description": "$Cluster2: Total number of entry evictions triggered by LRU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvictions{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Memory LRU Regions: Greedy Returns",
   "type": "table",
   "description": "$Cluster: Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=\"$Cluster\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Memory LRU Regions: Greedy Returns",
   "type": "table",
   "description": "$Cluster2: Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=\"$Cluster2\", category=\"MemLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}