{
 "title": "Dual Locators",
 "tags": [
  "dual gemfire",
  "locator",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "LocatorCluster",
    "label": "LocatorCluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "LocatorCluster2",
    "label": "LocatorCluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"locator\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 11, "x": 12, "y": 0 }
  },
  {
   "title": "$LocatorCluster: Cluster Up Time",
   "type": "stat",
   "description": "$LocatorCluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=~\"$LocatorCluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locator Count",
   "type": "stat",
   "description": "$LocatorCluster: Number of locators",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gemfire_locators{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Client Conn Requests",
   "type": "stat",
   "description": "$LocatorCluster: Highest number of client connection requests",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Cluster Up Time",
   "type": "stat",
   "description": "$LocatorCluster2: Cluster up time determined by the oldest member",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_process_uptime_seconds{$ClusterFilterLabel=~\"$LocatorCluster2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locator Count",
   "type": "stat",
   "description": "$LocatorCluster2: Number of locators",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gemfire_locators{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Client Conn Requests",
   "type": "stat",
   "description": "$LocatorCluster2: Highest number of client connection requests",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Client Conn Request Time",
   "type": "stat",
   "description": "$LocatorCluster: Highest client connection request time",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Requests In Progress",
   "type": "stat",
   "description": "$LocatorCluster:Highest number of locator requests in progress",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_requestsInProgress{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Client Conn Response Failures",
   "type": "stat",
   "description": "$LocatorCluster: Highest number of client connection response failures",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Client Conn Request Time",
   "type": "stat",
   "description": "$LocatorCluster2: Highest client connection request time",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Requests In Progress",
   "type": "stat",
   "description": "$LocatorCluster2:Highest number of locator requests in progress",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_requestsInProgress{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Client Conn Response Failures",
   "type": "stat",
   "description": "$LocatorCluster2: Highest number of client connection response failures",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators Resources",
   "type": "table",
   "description": "$LocatorCluster: Locator resource stats",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=~\"$LocatorCluster\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}/gemfire_maxMemory{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"VMStats\",exported_instance=\"vmStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"ParNew\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"ConcurrentMarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"PS Scavenge\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"PS MarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"G1 Young Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster\",exported_instance=\"G1 Old Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators Resources",
   "type": "table",
   "description": "$LocatorCluster2:Locator resource stats",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=~\"$LocatorCluster2\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}/gemfire_maxMemory{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"VMStats\",exported_instance=\"vmStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"ZGC Pauses\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"ZGC Cycles\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"ParNew\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"ConcurrentMarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"PS Scavenge\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"PS MarkSweep\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"G1 Young Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$LocatorCluster2\",exported_instance=\"G1 Old Generation\",member_type=\"locator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Client Connection",
   "type": "table",
   "description": "$LocatorCluster: Client connection request and response stats",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Client Connection",
   "type": "table",
   "description": "$LocatorCluster2: Client connection request and response stats",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientConnectionRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientConnectionResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Client Replacement",
   "type": "table",
   "description": "$LocatorCluster: Client replacement request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Client Replacement",
   "type": "table",
   "description": "$LocatorCluster:2 Client replacement request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_clientReplacementRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReplacementResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Find Coordinator",
   "type": "table",
   "description": "$LocatorCluster: Find coordinator request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_findCoordinatorRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Find Coordinator",
   "type": "table",
   "description": "$LocatorCluster2: Find coordinator request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_findCoordinatorRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_findCoordinatorResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Get All Servers",
   "type": "table",
   "description": "$LocatorCluster: Get all servers request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getAllServersRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Get All Servers",
   "type": "table",
   "description": "$LocatorCluster2: Get all servers request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getAllServersRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllServersResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Get View",
   "type": "table",
   "description": "$LocatorCluster: Get view request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getViewRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Get View",
   "type": "table",
   "description": "$LocatorCluster2: Get view request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_getViewRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getViewResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Locator List",
   "type": "table",
   "description": "$LocatorCluster: Locator list request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorListRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Locator List",
   "type": "table",
   "description": "$LocatorCluster2: Locator list request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorListRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorListResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Locator Status",
   "type": "table",
   "description": "$LocatorCluster: Locator status request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorStatusRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Locator Status",
   "type": "table",
   "description": "$LocatorCluster2: Locator status request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locatorStatusRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locatorStatusResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Queue Connection",
   "type": "table",
   "description": "$LocatorCluster: Queue connection request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queueConnectionRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequests{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponses{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Queue Connection",
   "type": "table",
   "description": "$LocatorCluster2: Queue connection request and response stats",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_queueConnectionRequestFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequestTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionRequests{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseFailures{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponseTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueConnectionResponses{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster: Locators: Processing, Servers, Locators",
   "type": "table",
   "description": "$LocatorCluster: Request and response processing time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_requestProcessingFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestProcessingTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestsInProgress{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingFailureTime{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingTime{$ClusterFilterLabel=~\"$LocatorCluster\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_serverLoadUpdates{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_servers{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=~\"$LocatorCluster\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$LocatorCluster2: Locators: Processing, Servers, Locators",
   "type": "table",
   "description": "$LocatorCluster2: Request and response processing time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_requestProcessingFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestProcessingTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_requestsInProgress{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingFailureTime{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_responseProcessingTime{$ClusterFilterLabel=~\"$LocatorCluster2\", category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_serverLoadUpdates{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_servers{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=~\"$LocatorCluster2\",category=\"LocatorStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}