{
 "title": "Dual Distributed Locks",
 "tags": [
  "dual gemfire",
  "messaging",
  "lock",
  "distribution"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Distributed Locks: Average Lock Release Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to release a lock per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Distributed Locks: Average Lock Release Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time took to release a lock per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}/gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Distributed Locks: Lock Releases In Progress",
   "type": "timeseries",
   "description": "$Cluster: Number of lock releases in progress per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockReleasesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Distributed Locks: Lock Releases In Progress",
   "type": "timeseries",
   "description": "$Cluster2: Number of lock releases in progress per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockReleasesInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Distributed Locks: Average Lock Wait Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to wait for a lock per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Distributed Locks: Average Lock Wait Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time took to wait for a lock per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}/gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Distributed Locks: Lock Waits In Progress",
   "type": "timeseries",
   "description": "$Cluster: Number of lock waits in progress per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitsInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster:2 Distributed Locks: Lock Waits In Progress",
   "type": "timeseries",
   "description": "$Cluster2: Number of lock waits in progress per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitsInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Distributed Locks: Average Lock Wait Failed Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took for a lock wait to fail per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Distributed Locks: Average Lock Wait Failed Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time took for a lock wait to fail per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}/gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Distributed Locks: Lock Waits Failed",
   "type": "timeseries",
   "description": "$Cluster: Number of lock waits failed per member.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Distributed Locks: Lock Waits Failed",
   "type": "timeseries",
   "description": "$Cluster2: Number of lock waits failed per member.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Distributed Locks Stats",
   "type": "table",
   "description": "$Cluster: Distributed Locks stats",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleasesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}/gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Distributed Locks Stats",
   "type": "table",
   "description": "$Cluster2: Distributed Locks stats",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}/gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleaseTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleasesCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockReleasesInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}/gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsInProgress{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}/gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitFailedTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_lockWaitsFailed{$ClusterFilterLabel=\"$Cluster2\",category=\"DLockStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}