{
 "title": "Dual CQ",
 "tags": [
  "dual gemfire",
  "cq",
  "dual compute",
  "dual cq"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Active CQ Count (Aggregate)",
   "type": "stat",
   "description": "$Cluster: Total number of active CQs across all servers.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_numCqsActive{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Average CQ Execution Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to complete a CQ execution.",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}/gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "{{instance}} Avg CQ Execution Time"
    }
   ]
  },
  {
   "title": "$Cluster2: Active CQ Count (Aggregate)",
   "type": "stat",
   "description": "$Cluster2: Total number of active CQs across all servers.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_numCqsActive{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Average CQ Execution Time",
   "type": "timeseries",
   "description": "$Cluster2: Average time took to complete a CQ execution.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}/gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "{{instance}} Avg CQ Execution Time"
    }
   ]
  },
  {
   "title": "$Cluster: Clients with CQs (Aggregate)",
   "type": "stat",
   "description": "$Cluster: Total number of clients with CQs across all servers.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_numClientsWithCqs{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Clients with CQs (Aggregate)",
   "type": "stat",
   "description": "$Cluster2: Total number of clients with CQs across all servers.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_numClientsWithCqs{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: CQ Service",
   "type": "table",
   "description": "$Cluster: CQ service stats.",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numClientsWithCqs{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqEventsFiltered{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsActive{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsClosed{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsCreated{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsOnClient{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsStopped{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numUniqueCqQuery{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: CQ Service",
   "type": "table",
   "description": "$Cluster2: CQ service stats.",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numClientsWithCqs{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqEventsFiltered{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsActive{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsClosed{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsCreated{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsOnClient{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsStopped{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numUniqueCqQuery{$ClusterFilterLabel=\"$Cluster2\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}